// Code generated by ent, DO NOT EDIT.

package preauthkey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/juanfont/headscale-v2/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldLTE(FieldID, id))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldEQ(FieldKey, v))
}

// Reusable applies equality check predicate on the "reusable" field. It's identical to ReusableEQ.
func Reusable(v bool) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldEQ(FieldReusable, v))
}

// Ephemeral applies equality check predicate on the "ephemeral" field. It's identical to EphemeralEQ.
func Ephemeral(v bool) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldEQ(FieldEphemeral, v))
}

// UsedCount applies equality check predicate on the "used_count" field. It's identical to UsedCountEQ.
func UsedCount(v int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldEQ(FieldUsedCount, v))
}

// Expiration applies equality check predicate on the "expiration" field. It's identical to ExpirationEQ.
func Expiration(v time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldEQ(FieldExpiration, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldEQ(FieldCreatedAt, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldContainsFold(FieldKey, v))
}

// ReusableEQ applies the EQ predicate on the "reusable" field.
func ReusableEQ(v bool) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldEQ(FieldReusable, v))
}

// ReusableNEQ applies the NEQ predicate on the "reusable" field.
func ReusableNEQ(v bool) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldNEQ(FieldReusable, v))
}

// EphemeralEQ applies the EQ predicate on the "ephemeral" field.
func EphemeralEQ(v bool) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldEQ(FieldEphemeral, v))
}

// EphemeralNEQ applies the NEQ predicate on the "ephemeral" field.
func EphemeralNEQ(v bool) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldNEQ(FieldEphemeral, v))
}

// UsedCountEQ applies the EQ predicate on the "used_count" field.
func UsedCountEQ(v int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldEQ(FieldUsedCount, v))
}

// UsedCountNEQ applies the NEQ predicate on the "used_count" field.
func UsedCountNEQ(v int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldNEQ(FieldUsedCount, v))
}

// UsedCountIn applies the In predicate on the "used_count" field.
func UsedCountIn(vs ...int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldIn(FieldUsedCount, vs...))
}

// UsedCountNotIn applies the NotIn predicate on the "used_count" field.
func UsedCountNotIn(vs ...int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldNotIn(FieldUsedCount, vs...))
}

// UsedCountGT applies the GT predicate on the "used_count" field.
func UsedCountGT(v int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldGT(FieldUsedCount, v))
}

// UsedCountGTE applies the GTE predicate on the "used_count" field.
func UsedCountGTE(v int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldGTE(FieldUsedCount, v))
}

// UsedCountLT applies the LT predicate on the "used_count" field.
func UsedCountLT(v int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldLT(FieldUsedCount, v))
}

// UsedCountLTE applies the LTE predicate on the "used_count" field.
func UsedCountLTE(v int) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldLTE(FieldUsedCount, v))
}

// ExpirationEQ applies the EQ predicate on the "expiration" field.
func ExpirationEQ(v time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldEQ(FieldExpiration, v))
}

// ExpirationNEQ applies the NEQ predicate on the "expiration" field.
func ExpirationNEQ(v time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldNEQ(FieldExpiration, v))
}

// ExpirationIn applies the In predicate on the "expiration" field.
func ExpirationIn(vs ...time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldIn(FieldExpiration, vs...))
}

// ExpirationNotIn applies the NotIn predicate on the "expiration" field.
func ExpirationNotIn(vs ...time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldNotIn(FieldExpiration, vs...))
}

// ExpirationGT applies the GT predicate on the "expiration" field.
func ExpirationGT(v time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldGT(FieldExpiration, v))
}

// ExpirationGTE applies the GTE predicate on the "expiration" field.
func ExpirationGTE(v time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldGTE(FieldExpiration, v))
}

// ExpirationLT applies the LT predicate on the "expiration" field.
func ExpirationLT(v time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldLT(FieldExpiration, v))
}

// ExpirationLTE applies the LTE predicate on the "expiration" field.
func ExpirationLTE(v time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldLTE(FieldExpiration, v))
}

// ExpirationIsNil applies the IsNil predicate on the "expiration" field.
func ExpirationIsNil() predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldIsNull(FieldExpiration))
}

// ExpirationNotNil applies the NotNil predicate on the "expiration" field.
func ExpirationNotNil() predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldNotNull(FieldExpiration))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldLTE(FieldCreatedAt, v))
}

// ACLTagsIsNil applies the IsNil predicate on the "acl_tags" field.
func ACLTagsIsNil() predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldIsNull(FieldACLTags))
}

// ACLTagsNotNil applies the NotNil predicate on the "acl_tags" field.
func ACLTagsNotNil() predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.FieldNotNull(FieldACLTags))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.PreAuthKey {
	return predicate.PreAuthKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.PreAuthKey {
	return predicate.PreAuthKey(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNodes applies the HasEdge predicate on the "nodes" edge.
func HasNodes() predicate.PreAuthKey {
	return predicate.PreAuthKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NodesTable, NodesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodesWith applies the HasEdge predicate on the "nodes" edge with a given conditions (other predicates).
func HasNodesWith(preds ...predicate.Node) predicate.PreAuthKey {
	return predicate.PreAuthKey(func(s *sql.Selector) {
		step := newNodesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PreAuthKey) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PreAuthKey) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PreAuthKey) predicate.PreAuthKey {
	return predicate.PreAuthKey(sql.NotPredicates(p))
}
