// Code generated by ent, DO NOT EDIT.

package aclpolicy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/juanfont/headscale-v2/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldEQ(FieldName, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldContainsFold(FieldName, v))
}

// PolicyEQ applies the EQ predicate on the "policy" field.
func PolicyEQ(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldEQ(FieldPolicy, v))
}

// PolicyNEQ applies the NEQ predicate on the "policy" field.
func PolicyNEQ(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldNEQ(FieldPolicy, v))
}

// PolicyIn applies the In predicate on the "policy" field.
func PolicyIn(vs ...string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldIn(FieldPolicy, vs...))
}

// PolicyNotIn applies the NotIn predicate on the "policy" field.
func PolicyNotIn(vs ...string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldNotIn(FieldPolicy, vs...))
}

// PolicyGT applies the GT predicate on the "policy" field.
func PolicyGT(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldGT(FieldPolicy, v))
}

// PolicyGTE applies the GTE predicate on the "policy" field.
func PolicyGTE(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldGTE(FieldPolicy, v))
}

// PolicyLT applies the LT predicate on the "policy" field.
func PolicyLT(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldLT(FieldPolicy, v))
}

// PolicyLTE applies the LTE predicate on the "policy" field.
func PolicyLTE(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldLTE(FieldPolicy, v))
}

// PolicyContains applies the Contains predicate on the "policy" field.
func PolicyContains(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldContains(FieldPolicy, v))
}

// PolicyHasPrefix applies the HasPrefix predicate on the "policy" field.
func PolicyHasPrefix(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldHasPrefix(FieldPolicy, v))
}

// PolicyHasSuffix applies the HasSuffix predicate on the "policy" field.
func PolicyHasSuffix(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldHasSuffix(FieldPolicy, v))
}

// PolicyEqualFold applies the EqualFold predicate on the "policy" field.
func PolicyEqualFold(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldEqualFold(FieldPolicy, v))
}

// PolicyContainsFold applies the ContainsFold predicate on the "policy" field.
func PolicyContainsFold(v string) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldContainsFold(FieldPolicy, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ACLPolicy) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ACLPolicy) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ACLPolicy) predicate.ACLPolicy {
	return predicate.ACLPolicy(sql.NotPredicates(p))
}
