// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: proto/v1/headscale.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHeadscaleServiceAuthApprove = "/headscale.v1.HeadscaleService/AuthApprove"
const OperationHeadscaleServiceAuthRegister = "/headscale.v1.HeadscaleService/AuthRegister"
const OperationHeadscaleServiceAuthReject = "/headscale.v1.HeadscaleService/AuthReject"
const OperationHeadscaleServiceBackfillNodeIPs = "/headscale.v1.HeadscaleService/BackfillNodeIPs"
const OperationHeadscaleServiceCreateApiKey = "/headscale.v1.HeadscaleService/CreateApiKey"
const OperationHeadscaleServiceCreatePreAuthKey = "/headscale.v1.HeadscaleService/CreatePreAuthKey"
const OperationHeadscaleServiceCreateUser = "/headscale.v1.HeadscaleService/CreateUser"
const OperationHeadscaleServiceDebugCreateNode = "/headscale.v1.HeadscaleService/DebugCreateNode"
const OperationHeadscaleServiceDeleteApiKey = "/headscale.v1.HeadscaleService/DeleteApiKey"
const OperationHeadscaleServiceDeleteNode = "/headscale.v1.HeadscaleService/DeleteNode"
const OperationHeadscaleServiceDeletePreAuthKey = "/headscale.v1.HeadscaleService/DeletePreAuthKey"
const OperationHeadscaleServiceDeleteUser = "/headscale.v1.HeadscaleService/DeleteUser"
const OperationHeadscaleServiceExpireApiKey = "/headscale.v1.HeadscaleService/ExpireApiKey"
const OperationHeadscaleServiceExpireNode = "/headscale.v1.HeadscaleService/ExpireNode"
const OperationHeadscaleServiceExpirePreAuthKey = "/headscale.v1.HeadscaleService/ExpirePreAuthKey"
const OperationHeadscaleServiceGetNode = "/headscale.v1.HeadscaleService/GetNode"
const OperationHeadscaleServiceGetPolicy = "/headscale.v1.HeadscaleService/GetPolicy"
const OperationHeadscaleServiceHealth = "/headscale.v1.HeadscaleService/Health"
const OperationHeadscaleServiceListApiKeys = "/headscale.v1.HeadscaleService/ListApiKeys"
const OperationHeadscaleServiceListNodes = "/headscale.v1.HeadscaleService/ListNodes"
const OperationHeadscaleServiceListPreAuthKeys = "/headscale.v1.HeadscaleService/ListPreAuthKeys"
const OperationHeadscaleServiceListUsers = "/headscale.v1.HeadscaleService/ListUsers"
const OperationHeadscaleServiceRegisterNode = "/headscale.v1.HeadscaleService/RegisterNode"
const OperationHeadscaleServiceRenameNode = "/headscale.v1.HeadscaleService/RenameNode"
const OperationHeadscaleServiceRenameUser = "/headscale.v1.HeadscaleService/RenameUser"
const OperationHeadscaleServiceSetApprovedRoutes = "/headscale.v1.HeadscaleService/SetApprovedRoutes"
const OperationHeadscaleServiceSetPolicy = "/headscale.v1.HeadscaleService/SetPolicy"
const OperationHeadscaleServiceSetTags = "/headscale.v1.HeadscaleService/SetTags"

type HeadscaleServiceHTTPServer interface {
	AuthApprove(context.Context, *AuthApproveRequest) (*AuthApproveResponse, error)
	// AuthRegister --- Auth start ---
	AuthRegister(context.Context, *AuthRegisterRequest) (*AuthRegisterResponse, error)
	AuthReject(context.Context, *AuthRejectRequest) (*AuthRejectResponse, error)
	BackfillNodeIPs(context.Context, *BackfillNodeIPsRequest) (*BackfillNodeIPsResponse, error)
	// CreateApiKey --- ApiKeys start ---
	CreateApiKey(context.Context, *CreateApiKeyRequest) (*CreateApiKeyResponse, error)
	// CreatePreAuthKey --- PreAuthKeys start ---
	CreatePreAuthKey(context.Context, *CreatePreAuthKeyRequest) (*CreatePreAuthKeyResponse, error)
	// CreateUser --- User start ---
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	// DebugCreateNode --- Node start ---
	DebugCreateNode(context.Context, *DebugCreateNodeRequest) (*DebugCreateNodeResponse, error)
	DeleteApiKey(context.Context, *DeleteApiKeyRequest) (*DeleteApiKeyResponse, error)
	DeleteNode(context.Context, *DeleteNodeRequest) (*DeleteNodeResponse, error)
	DeletePreAuthKey(context.Context, *DeletePreAuthKeyRequest) (*DeletePreAuthKeyResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	ExpireApiKey(context.Context, *ExpireApiKeyRequest) (*ExpireApiKeyResponse, error)
	ExpireNode(context.Context, *ExpireNodeRequest) (*ExpireNodeResponse, error)
	ExpirePreAuthKey(context.Context, *ExpirePreAuthKeyRequest) (*ExpirePreAuthKeyResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	// GetPolicy --- Policy start ---
	GetPolicy(context.Context, *GetPolicyRequest) (*GetPolicyResponse, error)
	// Health --- Health start ---
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	ListApiKeys(context.Context, *ListApiKeysRequest) (*ListApiKeysResponse, error)
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	ListPreAuthKeys(context.Context, *ListPreAuthKeysRequest) (*ListPreAuthKeysResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	RenameNode(context.Context, *RenameNodeRequest) (*RenameNodeResponse, error)
	RenameUser(context.Context, *RenameUserRequest) (*RenameUserResponse, error)
	SetApprovedRoutes(context.Context, *SetApprovedRoutesRequest) (*SetApprovedRoutesResponse, error)
	SetPolicy(context.Context, *SetPolicyRequest) (*SetPolicyResponse, error)
	SetTags(context.Context, *SetTagsRequest) (*SetTagsResponse, error)
}

func RegisterHeadscaleServiceHTTPServer(s *http.Server, srv HeadscaleServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/user", _HeadscaleService_CreateUser0_HTTP_Handler(srv))
	r.POST("/api/v1/user/{old_id}/rename/{new_name}", _HeadscaleService_RenameUser0_HTTP_Handler(srv))
	r.DELETE("/api/v1/user/{id}", _HeadscaleService_DeleteUser0_HTTP_Handler(srv))
	r.GET("/api/v1/user", _HeadscaleService_ListUsers0_HTTP_Handler(srv))
	r.POST("/api/v1/preauthkey", _HeadscaleService_CreatePreAuthKey0_HTTP_Handler(srv))
	r.POST("/api/v1/preauthkey/expire", _HeadscaleService_ExpirePreAuthKey0_HTTP_Handler(srv))
	r.DELETE("/api/v1/preauthkey", _HeadscaleService_DeletePreAuthKey0_HTTP_Handler(srv))
	r.GET("/api/v1/preauthkey", _HeadscaleService_ListPreAuthKeys0_HTTP_Handler(srv))
	r.POST("/api/v1/debug/node", _HeadscaleService_DebugCreateNode0_HTTP_Handler(srv))
	r.GET("/api/v1/node/{node_id}", _HeadscaleService_GetNode0_HTTP_Handler(srv))
	r.POST("/api/v1/node/{node_id}/tags", _HeadscaleService_SetTags0_HTTP_Handler(srv))
	r.POST("/api/v1/node/{node_id}/approve_routes", _HeadscaleService_SetApprovedRoutes0_HTTP_Handler(srv))
	r.POST("/api/v1/node/register", _HeadscaleService_RegisterNode0_HTTP_Handler(srv))
	r.DELETE("/api/v1/node/{node_id}", _HeadscaleService_DeleteNode0_HTTP_Handler(srv))
	r.POST("/api/v1/node/{node_id}/expire", _HeadscaleService_ExpireNode0_HTTP_Handler(srv))
	r.POST("/api/v1/node/{node_id}/rename/{new_name}", _HeadscaleService_RenameNode0_HTTP_Handler(srv))
	r.GET("/api/v1/node", _HeadscaleService_ListNodes0_HTTP_Handler(srv))
	r.POST("/api/v1/node/backfillips", _HeadscaleService_BackfillNodeIPs0_HTTP_Handler(srv))
	r.POST("/api/v1/auth/register", _HeadscaleService_AuthRegister0_HTTP_Handler(srv))
	r.POST("/api/v1/auth/approve", _HeadscaleService_AuthApprove0_HTTP_Handler(srv))
	r.POST("/api/v1/auth/reject", _HeadscaleService_AuthReject0_HTTP_Handler(srv))
	r.POST("/api/v1/apikey", _HeadscaleService_CreateApiKey0_HTTP_Handler(srv))
	r.POST("/api/v1/apikey/expire", _HeadscaleService_ExpireApiKey0_HTTP_Handler(srv))
	r.GET("/api/v1/apikey", _HeadscaleService_ListApiKeys0_HTTP_Handler(srv))
	r.DELETE("/api/v1/apikey/{prefix}", _HeadscaleService_DeleteApiKey0_HTTP_Handler(srv))
	r.GET("/api/v1/policy", _HeadscaleService_GetPolicy0_HTTP_Handler(srv))
	r.PUT("/api/v1/policy", _HeadscaleService_SetPolicy0_HTTP_Handler(srv))
	r.GET("/api/v1/health", _HeadscaleService_Health0_HTTP_Handler(srv))
}

func _HeadscaleService_CreateUser0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceCreateUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateUser(ctx, req.(*CreateUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateUserResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_RenameUser0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RenameUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceRenameUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RenameUser(ctx, req.(*RenameUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RenameUserResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_DeleteUser0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceDeleteUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteUser(ctx, req.(*DeleteUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteUserResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_ListUsers0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListUsersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceListUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUsers(ctx, req.(*ListUsersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListUsersResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_CreatePreAuthKey0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePreAuthKeyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceCreatePreAuthKey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePreAuthKey(ctx, req.(*CreatePreAuthKeyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreatePreAuthKeyResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_ExpirePreAuthKey0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExpirePreAuthKeyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceExpirePreAuthKey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExpirePreAuthKey(ctx, req.(*ExpirePreAuthKeyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExpirePreAuthKeyResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_DeletePreAuthKey0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeletePreAuthKeyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceDeletePreAuthKey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeletePreAuthKey(ctx, req.(*DeletePreAuthKeyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeletePreAuthKeyResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_ListPreAuthKeys0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPreAuthKeysRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceListPreAuthKeys)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPreAuthKeys(ctx, req.(*ListPreAuthKeysRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPreAuthKeysResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_DebugCreateNode0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DebugCreateNodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceDebugCreateNode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DebugCreateNode(ctx, req.(*DebugCreateNodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DebugCreateNodeResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_GetNode0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceGetNode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNode(ctx, req.(*GetNodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetNodeResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_SetTags0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetTagsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceSetTags)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetTags(ctx, req.(*SetTagsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetTagsResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_SetApprovedRoutes0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetApprovedRoutesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceSetApprovedRoutes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetApprovedRoutes(ctx, req.(*SetApprovedRoutesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetApprovedRoutesResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_RegisterNode0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterNodeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceRegisterNode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterNode(ctx, req.(*RegisterNodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RegisterNodeResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_DeleteNode0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteNodeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceDeleteNode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteNode(ctx, req.(*DeleteNodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteNodeResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_ExpireNode0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExpireNodeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceExpireNode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExpireNode(ctx, req.(*ExpireNodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExpireNodeResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_RenameNode0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RenameNodeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceRenameNode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RenameNode(ctx, req.(*RenameNodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RenameNodeResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_ListNodes0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListNodesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceListNodes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNodes(ctx, req.(*ListNodesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListNodesResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_BackfillNodeIPs0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BackfillNodeIPsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceBackfillNodeIPs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BackfillNodeIPs(ctx, req.(*BackfillNodeIPsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BackfillNodeIPsResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_AuthRegister0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AuthRegisterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceAuthRegister)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AuthRegister(ctx, req.(*AuthRegisterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AuthRegisterResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_AuthApprove0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AuthApproveRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceAuthApprove)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AuthApprove(ctx, req.(*AuthApproveRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AuthApproveResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_AuthReject0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AuthRejectRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceAuthReject)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AuthReject(ctx, req.(*AuthRejectRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AuthRejectResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_CreateApiKey0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateApiKeyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceCreateApiKey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateApiKey(ctx, req.(*CreateApiKeyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateApiKeyResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_ExpireApiKey0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExpireApiKeyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceExpireApiKey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExpireApiKey(ctx, req.(*ExpireApiKeyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExpireApiKeyResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_ListApiKeys0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListApiKeysRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceListApiKeys)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListApiKeys(ctx, req.(*ListApiKeysRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListApiKeysResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_DeleteApiKey0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteApiKeyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceDeleteApiKey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteApiKey(ctx, req.(*DeleteApiKeyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteApiKeyResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_GetPolicy0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPolicyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceGetPolicy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPolicy(ctx, req.(*GetPolicyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPolicyResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_SetPolicy0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetPolicyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceSetPolicy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetPolicy(ctx, req.(*SetPolicyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetPolicyResponse)
		return ctx.Result(200, reply)
	}
}

func _HeadscaleService_Health0_HTTP_Handler(srv HeadscaleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HealthRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeadscaleServiceHealth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Health(ctx, req.(*HealthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HealthResponse)
		return ctx.Result(200, reply)
	}
}

type HeadscaleServiceHTTPClient interface {
	AuthApprove(ctx context.Context, req *AuthApproveRequest, opts ...http.CallOption) (rsp *AuthApproveResponse, err error)
	// AuthRegister --- Auth start ---
	AuthRegister(ctx context.Context, req *AuthRegisterRequest, opts ...http.CallOption) (rsp *AuthRegisterResponse, err error)
	AuthReject(ctx context.Context, req *AuthRejectRequest, opts ...http.CallOption) (rsp *AuthRejectResponse, err error)
	BackfillNodeIPs(ctx context.Context, req *BackfillNodeIPsRequest, opts ...http.CallOption) (rsp *BackfillNodeIPsResponse, err error)
	// CreateApiKey --- ApiKeys start ---
	CreateApiKey(ctx context.Context, req *CreateApiKeyRequest, opts ...http.CallOption) (rsp *CreateApiKeyResponse, err error)
	// CreatePreAuthKey --- PreAuthKeys start ---
	CreatePreAuthKey(ctx context.Context, req *CreatePreAuthKeyRequest, opts ...http.CallOption) (rsp *CreatePreAuthKeyResponse, err error)
	// CreateUser --- User start ---
	CreateUser(ctx context.Context, req *CreateUserRequest, opts ...http.CallOption) (rsp *CreateUserResponse, err error)
	// DebugCreateNode --- Node start ---
	DebugCreateNode(ctx context.Context, req *DebugCreateNodeRequest, opts ...http.CallOption) (rsp *DebugCreateNodeResponse, err error)
	DeleteApiKey(ctx context.Context, req *DeleteApiKeyRequest, opts ...http.CallOption) (rsp *DeleteApiKeyResponse, err error)
	DeleteNode(ctx context.Context, req *DeleteNodeRequest, opts ...http.CallOption) (rsp *DeleteNodeResponse, err error)
	DeletePreAuthKey(ctx context.Context, req *DeletePreAuthKeyRequest, opts ...http.CallOption) (rsp *DeletePreAuthKeyResponse, err error)
	DeleteUser(ctx context.Context, req *DeleteUserRequest, opts ...http.CallOption) (rsp *DeleteUserResponse, err error)
	ExpireApiKey(ctx context.Context, req *ExpireApiKeyRequest, opts ...http.CallOption) (rsp *ExpireApiKeyResponse, err error)
	ExpireNode(ctx context.Context, req *ExpireNodeRequest, opts ...http.CallOption) (rsp *ExpireNodeResponse, err error)
	ExpirePreAuthKey(ctx context.Context, req *ExpirePreAuthKeyRequest, opts ...http.CallOption) (rsp *ExpirePreAuthKeyResponse, err error)
	GetNode(ctx context.Context, req *GetNodeRequest, opts ...http.CallOption) (rsp *GetNodeResponse, err error)
	// GetPolicy --- Policy start ---
	GetPolicy(ctx context.Context, req *GetPolicyRequest, opts ...http.CallOption) (rsp *GetPolicyResponse, err error)
	// Health --- Health start ---
	Health(ctx context.Context, req *HealthRequest, opts ...http.CallOption) (rsp *HealthResponse, err error)
	ListApiKeys(ctx context.Context, req *ListApiKeysRequest, opts ...http.CallOption) (rsp *ListApiKeysResponse, err error)
	ListNodes(ctx context.Context, req *ListNodesRequest, opts ...http.CallOption) (rsp *ListNodesResponse, err error)
	ListPreAuthKeys(ctx context.Context, req *ListPreAuthKeysRequest, opts ...http.CallOption) (rsp *ListPreAuthKeysResponse, err error)
	ListUsers(ctx context.Context, req *ListUsersRequest, opts ...http.CallOption) (rsp *ListUsersResponse, err error)
	RegisterNode(ctx context.Context, req *RegisterNodeRequest, opts ...http.CallOption) (rsp *RegisterNodeResponse, err error)
	RenameNode(ctx context.Context, req *RenameNodeRequest, opts ...http.CallOption) (rsp *RenameNodeResponse, err error)
	RenameUser(ctx context.Context, req *RenameUserRequest, opts ...http.CallOption) (rsp *RenameUserResponse, err error)
	SetApprovedRoutes(ctx context.Context, req *SetApprovedRoutesRequest, opts ...http.CallOption) (rsp *SetApprovedRoutesResponse, err error)
	SetPolicy(ctx context.Context, req *SetPolicyRequest, opts ...http.CallOption) (rsp *SetPolicyResponse, err error)
	SetTags(ctx context.Context, req *SetTagsRequest, opts ...http.CallOption) (rsp *SetTagsResponse, err error)
}

type HeadscaleServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewHeadscaleServiceHTTPClient(client *http.Client) HeadscaleServiceHTTPClient {
	return &HeadscaleServiceHTTPClientImpl{client}
}

func (c *HeadscaleServiceHTTPClientImpl) AuthApprove(ctx context.Context, in *AuthApproveRequest, opts ...http.CallOption) (*AuthApproveResponse, error) {
	var out AuthApproveResponse
	pattern := "/api/v1/auth/approve"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHeadscaleServiceAuthApprove))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// AuthRegister --- Auth start ---
func (c *HeadscaleServiceHTTPClientImpl) AuthRegister(ctx context.Context, in *AuthRegisterRequest, opts ...http.CallOption) (*AuthRegisterResponse, error) {
	var out AuthRegisterResponse
	pattern := "/api/v1/auth/register"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHeadscaleServiceAuthRegister))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) AuthReject(ctx context.Context, in *AuthRejectRequest, opts ...http.CallOption) (*AuthRejectResponse, error) {
	var out AuthRejectResponse
	pattern := "/api/v1/auth/reject"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHeadscaleServiceAuthReject))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) BackfillNodeIPs(ctx context.Context, in *BackfillNodeIPsRequest, opts ...http.CallOption) (*BackfillNodeIPsResponse, error) {
	var out BackfillNodeIPsResponse
	pattern := "/api/v1/node/backfillips"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeadscaleServiceBackfillNodeIPs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateApiKey --- ApiKeys start ---
func (c *HeadscaleServiceHTTPClientImpl) CreateApiKey(ctx context.Context, in *CreateApiKeyRequest, opts ...http.CallOption) (*CreateApiKeyResponse, error) {
	var out CreateApiKeyResponse
	pattern := "/api/v1/apikey"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHeadscaleServiceCreateApiKey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreatePreAuthKey --- PreAuthKeys start ---
func (c *HeadscaleServiceHTTPClientImpl) CreatePreAuthKey(ctx context.Context, in *CreatePreAuthKeyRequest, opts ...http.CallOption) (*CreatePreAuthKeyResponse, error) {
	var out CreatePreAuthKeyResponse
	pattern := "/api/v1/preauthkey"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHeadscaleServiceCreatePreAuthKey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateUser --- User start ---
func (c *HeadscaleServiceHTTPClientImpl) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...http.CallOption) (*CreateUserResponse, error) {
	var out CreateUserResponse
	pattern := "/api/v1/user"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHeadscaleServiceCreateUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DebugCreateNode --- Node start ---
func (c *HeadscaleServiceHTTPClientImpl) DebugCreateNode(ctx context.Context, in *DebugCreateNodeRequest, opts ...http.CallOption) (*DebugCreateNodeResponse, error) {
	var out DebugCreateNodeResponse
	pattern := "/api/v1/debug/node"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHeadscaleServiceDebugCreateNode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) DeleteApiKey(ctx context.Context, in *DeleteApiKeyRequest, opts ...http.CallOption) (*DeleteApiKeyResponse, error) {
	var out DeleteApiKeyResponse
	pattern := "/api/v1/apikey/{prefix}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeadscaleServiceDeleteApiKey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...http.CallOption) (*DeleteNodeResponse, error) {
	var out DeleteNodeResponse
	pattern := "/api/v1/node/{node_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeadscaleServiceDeleteNode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) DeletePreAuthKey(ctx context.Context, in *DeletePreAuthKeyRequest, opts ...http.CallOption) (*DeletePreAuthKeyResponse, error) {
	var out DeletePreAuthKeyResponse
	pattern := "/api/v1/preauthkey"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeadscaleServiceDeletePreAuthKey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...http.CallOption) (*DeleteUserResponse, error) {
	var out DeleteUserResponse
	pattern := "/api/v1/user/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeadscaleServiceDeleteUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) ExpireApiKey(ctx context.Context, in *ExpireApiKeyRequest, opts ...http.CallOption) (*ExpireApiKeyResponse, error) {
	var out ExpireApiKeyResponse
	pattern := "/api/v1/apikey/expire"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHeadscaleServiceExpireApiKey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) ExpireNode(ctx context.Context, in *ExpireNodeRequest, opts ...http.CallOption) (*ExpireNodeResponse, error) {
	var out ExpireNodeResponse
	pattern := "/api/v1/node/{node_id}/expire"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeadscaleServiceExpireNode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) ExpirePreAuthKey(ctx context.Context, in *ExpirePreAuthKeyRequest, opts ...http.CallOption) (*ExpirePreAuthKeyResponse, error) {
	var out ExpirePreAuthKeyResponse
	pattern := "/api/v1/preauthkey/expire"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHeadscaleServiceExpirePreAuthKey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) GetNode(ctx context.Context, in *GetNodeRequest, opts ...http.CallOption) (*GetNodeResponse, error) {
	var out GetNodeResponse
	pattern := "/api/v1/node/{node_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeadscaleServiceGetNode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPolicy --- Policy start ---
func (c *HeadscaleServiceHTTPClientImpl) GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...http.CallOption) (*GetPolicyResponse, error) {
	var out GetPolicyResponse
	pattern := "/api/v1/policy"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeadscaleServiceGetPolicy))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Health --- Health start ---
func (c *HeadscaleServiceHTTPClientImpl) Health(ctx context.Context, in *HealthRequest, opts ...http.CallOption) (*HealthResponse, error) {
	var out HealthResponse
	pattern := "/api/v1/health"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeadscaleServiceHealth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) ListApiKeys(ctx context.Context, in *ListApiKeysRequest, opts ...http.CallOption) (*ListApiKeysResponse, error) {
	var out ListApiKeysResponse
	pattern := "/api/v1/apikey"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeadscaleServiceListApiKeys))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...http.CallOption) (*ListNodesResponse, error) {
	var out ListNodesResponse
	pattern := "/api/v1/node"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeadscaleServiceListNodes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) ListPreAuthKeys(ctx context.Context, in *ListPreAuthKeysRequest, opts ...http.CallOption) (*ListPreAuthKeysResponse, error) {
	var out ListPreAuthKeysResponse
	pattern := "/api/v1/preauthkey"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeadscaleServiceListPreAuthKeys))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...http.CallOption) (*ListUsersResponse, error) {
	var out ListUsersResponse
	pattern := "/api/v1/user"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeadscaleServiceListUsers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...http.CallOption) (*RegisterNodeResponse, error) {
	var out RegisterNodeResponse
	pattern := "/api/v1/node/register"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeadscaleServiceRegisterNode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) RenameNode(ctx context.Context, in *RenameNodeRequest, opts ...http.CallOption) (*RenameNodeResponse, error) {
	var out RenameNodeResponse
	pattern := "/api/v1/node/{node_id}/rename/{new_name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeadscaleServiceRenameNode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) RenameUser(ctx context.Context, in *RenameUserRequest, opts ...http.CallOption) (*RenameUserResponse, error) {
	var out RenameUserResponse
	pattern := "/api/v1/user/{old_id}/rename/{new_name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeadscaleServiceRenameUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) SetApprovedRoutes(ctx context.Context, in *SetApprovedRoutesRequest, opts ...http.CallOption) (*SetApprovedRoutesResponse, error) {
	var out SetApprovedRoutesResponse
	pattern := "/api/v1/node/{node_id}/approve_routes"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHeadscaleServiceSetApprovedRoutes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) SetPolicy(ctx context.Context, in *SetPolicyRequest, opts ...http.CallOption) (*SetPolicyResponse, error) {
	var out SetPolicyResponse
	pattern := "/api/v1/policy"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHeadscaleServiceSetPolicy))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HeadscaleServiceHTTPClientImpl) SetTags(ctx context.Context, in *SetTagsRequest, opts ...http.CallOption) (*SetTagsResponse, error) {
	var out SetTagsResponse
	pattern := "/api/v1/node/{node_id}/tags"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHeadscaleServiceSetTags))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
