// Code generated by ent, DO NOT EDIT.

package node

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the node type in the database.
	Label = "node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMachineKey holds the string denoting the machine_key field in the database.
	FieldMachineKey = "machine_key"
	// FieldNodeKey holds the string denoting the node_key field in the database.
	FieldNodeKey = "node_key"
	// FieldDiscoKey holds the string denoting the disco_key field in the database.
	FieldDiscoKey = "disco_key"
	// FieldEndpoints holds the string denoting the endpoints field in the database.
	FieldEndpoints = "endpoints"
	// FieldHostinfo holds the string denoting the hostinfo field in the database.
	FieldHostinfo = "hostinfo"
	// FieldIPAddresses holds the string denoting the ip_addresses field in the database.
	FieldIPAddresses = "ip_addresses"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldGivenName holds the string denoting the given_name field in the database.
	FieldGivenName = "given_name"
	// FieldLastSeen holds the string denoting the last_seen field in the database.
	FieldLastSeen = "last_seen"
	// FieldExpiry holds the string denoting the expiry field in the database.
	FieldExpiry = "expiry"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRegisterMethod holds the string denoting the register_method field in the database.
	FieldRegisterMethod = "register_method"
	// FieldApprovedRoutes holds the string denoting the approved_routes field in the database.
	FieldApprovedRoutes = "approved_routes"
	// FieldAvailableRoutes holds the string denoting the available_routes field in the database.
	FieldAvailableRoutes = "available_routes"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldIsOnline holds the string denoting the is_online field in the database.
	FieldIsOnline = "is_online"
	// FieldEphemeral holds the string denoting the ephemeral field in the database.
	FieldEphemeral = "ephemeral"
	// FieldSessionEpoch holds the string denoting the session_epoch field in the database.
	FieldSessionEpoch = "session_epoch"
	// FieldNodeID holds the string denoting the node_id field in the database.
	FieldNodeID = "node_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgePreAuthKey holds the string denoting the pre_auth_key edge name in mutations.
	EdgePreAuthKey = "pre_auth_key"
	// Table holds the table name of the node in the database.
	Table = "nodes"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "nodes"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// PreAuthKeyTable is the table that holds the pre_auth_key relation/edge.
	PreAuthKeyTable = "nodes"
	// PreAuthKeyInverseTable is the table name for the PreAuthKey entity.
	// It exists in this package in order to avoid circular dependency with the "preauthkey" package.
	PreAuthKeyInverseTable = "pre_auth_keys"
	// PreAuthKeyColumn is the table column denoting the pre_auth_key relation/edge.
	PreAuthKeyColumn = "pre_auth_key_nodes"
)

// Columns holds all SQL columns for node fields.
var Columns = []string{
	FieldID,
	FieldMachineKey,
	FieldNodeKey,
	FieldDiscoKey,
	FieldEndpoints,
	FieldHostinfo,
	FieldIPAddresses,
	FieldName,
	FieldGivenName,
	FieldLastSeen,
	FieldExpiry,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRegisterMethod,
	FieldApprovedRoutes,
	FieldAvailableRoutes,
	FieldTags,
	FieldIsOnline,
	FieldEphemeral,
	FieldSessionEpoch,
	FieldNodeID,
	FieldUserID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "nodes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"pre_auth_key_nodes",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// MachineKeyValidator is a validator for the "machine_key" field. It is called by the builders before save.
	MachineKeyValidator func(string) error
	// NodeKeyValidator is a validator for the "node_key" field. It is called by the builders before save.
	NodeKeyValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultRegisterMethod holds the default value on creation for the "register_method" field.
	DefaultRegisterMethod string
	// DefaultIsOnline holds the default value on creation for the "is_online" field.
	DefaultIsOnline bool
	// DefaultEphemeral holds the default value on creation for the "ephemeral" field.
	DefaultEphemeral bool
	// DefaultSessionEpoch holds the default value on creation for the "session_epoch" field.
	DefaultSessionEpoch uint64
)

// OrderOption defines the ordering options for the Node queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMachineKey orders the results by the machine_key field.
func ByMachineKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMachineKey, opts...).ToFunc()
}

// ByNodeKey orders the results by the node_key field.
func ByNodeKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeKey, opts...).ToFunc()
}

// ByDiscoKey orders the results by the disco_key field.
func ByDiscoKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscoKey, opts...).ToFunc()
}

// ByHostinfo orders the results by the hostinfo field.
func ByHostinfo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostinfo, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByGivenName orders the results by the given_name field.
func ByGivenName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGivenName, opts...).ToFunc()
}

// ByLastSeen orders the results by the last_seen field.
func ByLastSeen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeen, opts...).ToFunc()
}

// ByExpiry orders the results by the expiry field.
func ByExpiry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiry, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRegisterMethod orders the results by the register_method field.
func ByRegisterMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegisterMethod, opts...).ToFunc()
}

// ByIsOnline orders the results by the is_online field.
func ByIsOnline(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsOnline, opts...).ToFunc()
}

// ByEphemeral orders the results by the ephemeral field.
func ByEphemeral(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEphemeral, opts...).ToFunc()
}

// BySessionEpoch orders the results by the session_epoch field.
func BySessionEpoch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionEpoch, opts...).ToFunc()
}

// ByNodeID orders the results by the node_id field.
func ByNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByPreAuthKeyField orders the results by pre_auth_key field.
func ByPreAuthKeyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPreAuthKeyStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newPreAuthKeyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PreAuthKeyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PreAuthKeyTable, PreAuthKeyColumn),
	)
}
