// Code generated by ent, DO NOT EDIT.

package node

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/juanfont/headscale-v2/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldID, id))
}

// MachineKey applies equality check predicate on the "machine_key" field. It's identical to MachineKeyEQ.
func MachineKey(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldMachineKey, v))
}

// NodeKey applies equality check predicate on the "node_key" field. It's identical to NodeKeyEQ.
func NodeKey(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldNodeKey, v))
}

// DiscoKey applies equality check predicate on the "disco_key" field. It's identical to DiscoKeyEQ.
func DiscoKey(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldDiscoKey, v))
}

// Hostinfo applies equality check predicate on the "hostinfo" field. It's identical to HostinfoEQ.
func Hostinfo(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldHostinfo, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldName, v))
}

// GivenName applies equality check predicate on the "given_name" field. It's identical to GivenNameEQ.
func GivenName(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldGivenName, v))
}

// LastSeen applies equality check predicate on the "last_seen" field. It's identical to LastSeenEQ.
func LastSeen(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldLastSeen, v))
}

// Expiry applies equality check predicate on the "expiry" field. It's identical to ExpiryEQ.
func Expiry(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldExpiry, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldUpdatedAt, v))
}

// RegisterMethod applies equality check predicate on the "register_method" field. It's identical to RegisterMethodEQ.
func RegisterMethod(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldRegisterMethod, v))
}

// IsOnline applies equality check predicate on the "is_online" field. It's identical to IsOnlineEQ.
func IsOnline(v bool) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldIsOnline, v))
}

// Ephemeral applies equality check predicate on the "ephemeral" field. It's identical to EphemeralEQ.
func Ephemeral(v bool) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldEphemeral, v))
}

// SessionEpoch applies equality check predicate on the "session_epoch" field. It's identical to SessionEpochEQ.
func SessionEpoch(v uint64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldSessionEpoch, v))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldNodeID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldUserID, v))
}

// MachineKeyEQ applies the EQ predicate on the "machine_key" field.
func MachineKeyEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldMachineKey, v))
}

// MachineKeyNEQ applies the NEQ predicate on the "machine_key" field.
func MachineKeyNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldMachineKey, v))
}

// MachineKeyIn applies the In predicate on the "machine_key" field.
func MachineKeyIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldMachineKey, vs...))
}

// MachineKeyNotIn applies the NotIn predicate on the "machine_key" field.
func MachineKeyNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldMachineKey, vs...))
}

// MachineKeyGT applies the GT predicate on the "machine_key" field.
func MachineKeyGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldMachineKey, v))
}

// MachineKeyGTE applies the GTE predicate on the "machine_key" field.
func MachineKeyGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldMachineKey, v))
}

// MachineKeyLT applies the LT predicate on the "machine_key" field.
func MachineKeyLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldMachineKey, v))
}

// MachineKeyLTE applies the LTE predicate on the "machine_key" field.
func MachineKeyLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldMachineKey, v))
}

// MachineKeyContains applies the Contains predicate on the "machine_key" field.
func MachineKeyContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldMachineKey, v))
}

// MachineKeyHasPrefix applies the HasPrefix predicate on the "machine_key" field.
func MachineKeyHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldMachineKey, v))
}

// MachineKeyHasSuffix applies the HasSuffix predicate on the "machine_key" field.
func MachineKeyHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldMachineKey, v))
}

// MachineKeyEqualFold applies the EqualFold predicate on the "machine_key" field.
func MachineKeyEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldMachineKey, v))
}

// MachineKeyContainsFold applies the ContainsFold predicate on the "machine_key" field.
func MachineKeyContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldMachineKey, v))
}

// NodeKeyEQ applies the EQ predicate on the "node_key" field.
func NodeKeyEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldNodeKey, v))
}

// NodeKeyNEQ applies the NEQ predicate on the "node_key" field.
func NodeKeyNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldNodeKey, v))
}

// NodeKeyIn applies the In predicate on the "node_key" field.
func NodeKeyIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldNodeKey, vs...))
}

// NodeKeyNotIn applies the NotIn predicate on the "node_key" field.
func NodeKeyNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldNodeKey, vs...))
}

// NodeKeyGT applies the GT predicate on the "node_key" field.
func NodeKeyGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldNodeKey, v))
}

// NodeKeyGTE applies the GTE predicate on the "node_key" field.
func NodeKeyGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldNodeKey, v))
}

// NodeKeyLT applies the LT predicate on the "node_key" field.
func NodeKeyLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldNodeKey, v))
}

// NodeKeyLTE applies the LTE predicate on the "node_key" field.
func NodeKeyLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldNodeKey, v))
}

// NodeKeyContains applies the Contains predicate on the "node_key" field.
func NodeKeyContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldNodeKey, v))
}

// NodeKeyHasPrefix applies the HasPrefix predicate on the "node_key" field.
func NodeKeyHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldNodeKey, v))
}

// NodeKeyHasSuffix applies the HasSuffix predicate on the "node_key" field.
func NodeKeyHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldNodeKey, v))
}

// NodeKeyEqualFold applies the EqualFold predicate on the "node_key" field.
func NodeKeyEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldNodeKey, v))
}

// NodeKeyContainsFold applies the ContainsFold predicate on the "node_key" field.
func NodeKeyContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldNodeKey, v))
}

// DiscoKeyEQ applies the EQ predicate on the "disco_key" field.
func DiscoKeyEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldDiscoKey, v))
}

// DiscoKeyNEQ applies the NEQ predicate on the "disco_key" field.
func DiscoKeyNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldDiscoKey, v))
}

// DiscoKeyIn applies the In predicate on the "disco_key" field.
func DiscoKeyIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldDiscoKey, vs...))
}

// DiscoKeyNotIn applies the NotIn predicate on the "disco_key" field.
func DiscoKeyNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldDiscoKey, vs...))
}

// DiscoKeyGT applies the GT predicate on the "disco_key" field.
func DiscoKeyGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldDiscoKey, v))
}

// DiscoKeyGTE applies the GTE predicate on the "disco_key" field.
func DiscoKeyGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldDiscoKey, v))
}

// DiscoKeyLT applies the LT predicate on the "disco_key" field.
func DiscoKeyLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldDiscoKey, v))
}

// DiscoKeyLTE applies the LTE predicate on the "disco_key" field.
func DiscoKeyLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldDiscoKey, v))
}

// DiscoKeyContains applies the Contains predicate on the "disco_key" field.
func DiscoKeyContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldDiscoKey, v))
}

// DiscoKeyHasPrefix applies the HasPrefix predicate on the "disco_key" field.
func DiscoKeyHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldDiscoKey, v))
}

// DiscoKeyHasSuffix applies the HasSuffix predicate on the "disco_key" field.
func DiscoKeyHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldDiscoKey, v))
}

// DiscoKeyIsNil applies the IsNil predicate on the "disco_key" field.
func DiscoKeyIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldDiscoKey))
}

// DiscoKeyNotNil applies the NotNil predicate on the "disco_key" field.
func DiscoKeyNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldDiscoKey))
}

// DiscoKeyEqualFold applies the EqualFold predicate on the "disco_key" field.
func DiscoKeyEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldDiscoKey, v))
}

// DiscoKeyContainsFold applies the ContainsFold predicate on the "disco_key" field.
func DiscoKeyContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldDiscoKey, v))
}

// EndpointsIsNil applies the IsNil predicate on the "endpoints" field.
func EndpointsIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldEndpoints))
}

// EndpointsNotNil applies the NotNil predicate on the "endpoints" field.
func EndpointsNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldEndpoints))
}

// HostinfoEQ applies the EQ predicate on the "hostinfo" field.
func HostinfoEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldHostinfo, v))
}

// HostinfoNEQ applies the NEQ predicate on the "hostinfo" field.
func HostinfoNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldHostinfo, v))
}

// HostinfoIn applies the In predicate on the "hostinfo" field.
func HostinfoIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldHostinfo, vs...))
}

// HostinfoNotIn applies the NotIn predicate on the "hostinfo" field.
func HostinfoNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldHostinfo, vs...))
}

// HostinfoGT applies the GT predicate on the "hostinfo" field.
func HostinfoGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldHostinfo, v))
}

// HostinfoGTE applies the GTE predicate on the "hostinfo" field.
func HostinfoGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldHostinfo, v))
}

// HostinfoLT applies the LT predicate on the "hostinfo" field.
func HostinfoLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldHostinfo, v))
}

// HostinfoLTE applies the LTE predicate on the "hostinfo" field.
func HostinfoLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldHostinfo, v))
}

// HostinfoContains applies the Contains predicate on the "hostinfo" field.
func HostinfoContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldHostinfo, v))
}

// HostinfoHasPrefix applies the HasPrefix predicate on the "hostinfo" field.
func HostinfoHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldHostinfo, v))
}

// HostinfoHasSuffix applies the HasSuffix predicate on the "hostinfo" field.
func HostinfoHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldHostinfo, v))
}

// HostinfoIsNil applies the IsNil predicate on the "hostinfo" field.
func HostinfoIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldHostinfo))
}

// HostinfoNotNil applies the NotNil predicate on the "hostinfo" field.
func HostinfoNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldHostinfo))
}

// HostinfoEqualFold applies the EqualFold predicate on the "hostinfo" field.
func HostinfoEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldHostinfo, v))
}

// HostinfoContainsFold applies the ContainsFold predicate on the "hostinfo" field.
func HostinfoContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldHostinfo, v))
}

// IPAddressesIsNil applies the IsNil predicate on the "ip_addresses" field.
func IPAddressesIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldIPAddresses))
}

// IPAddressesNotNil applies the NotNil predicate on the "ip_addresses" field.
func IPAddressesNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldIPAddresses))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldName, v))
}

// GivenNameEQ applies the EQ predicate on the "given_name" field.
func GivenNameEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldGivenName, v))
}

// GivenNameNEQ applies the NEQ predicate on the "given_name" field.
func GivenNameNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldGivenName, v))
}

// GivenNameIn applies the In predicate on the "given_name" field.
func GivenNameIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldGivenName, vs...))
}

// GivenNameNotIn applies the NotIn predicate on the "given_name" field.
func GivenNameNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldGivenName, vs...))
}

// GivenNameGT applies the GT predicate on the "given_name" field.
func GivenNameGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldGivenName, v))
}

// GivenNameGTE applies the GTE predicate on the "given_name" field.
func GivenNameGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldGivenName, v))
}

// GivenNameLT applies the LT predicate on the "given_name" field.
func GivenNameLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldGivenName, v))
}

// GivenNameLTE applies the LTE predicate on the "given_name" field.
func GivenNameLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldGivenName, v))
}

// GivenNameContains applies the Contains predicate on the "given_name" field.
func GivenNameContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldGivenName, v))
}

// GivenNameHasPrefix applies the HasPrefix predicate on the "given_name" field.
func GivenNameHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldGivenName, v))
}

// GivenNameHasSuffix applies the HasSuffix predicate on the "given_name" field.
func GivenNameHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldGivenName, v))
}

// GivenNameIsNil applies the IsNil predicate on the "given_name" field.
func GivenNameIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldGivenName))
}

// GivenNameNotNil applies the NotNil predicate on the "given_name" field.
func GivenNameNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldGivenName))
}

// GivenNameEqualFold applies the EqualFold predicate on the "given_name" field.
func GivenNameEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldGivenName, v))
}

// GivenNameContainsFold applies the ContainsFold predicate on the "given_name" field.
func GivenNameContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldGivenName, v))
}

// LastSeenEQ applies the EQ predicate on the "last_seen" field.
func LastSeenEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldLastSeen, v))
}

// LastSeenNEQ applies the NEQ predicate on the "last_seen" field.
func LastSeenNEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldLastSeen, v))
}

// LastSeenIn applies the In predicate on the "last_seen" field.
func LastSeenIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldLastSeen, vs...))
}

// LastSeenNotIn applies the NotIn predicate on the "last_seen" field.
func LastSeenNotIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldLastSeen, vs...))
}

// LastSeenGT applies the GT predicate on the "last_seen" field.
func LastSeenGT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldLastSeen, v))
}

// LastSeenGTE applies the GTE predicate on the "last_seen" field.
func LastSeenGTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldLastSeen, v))
}

// LastSeenLT applies the LT predicate on the "last_seen" field.
func LastSeenLT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldLastSeen, v))
}

// LastSeenLTE applies the LTE predicate on the "last_seen" field.
func LastSeenLTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldLastSeen, v))
}

// LastSeenIsNil applies the IsNil predicate on the "last_seen" field.
func LastSeenIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldLastSeen))
}

// LastSeenNotNil applies the NotNil predicate on the "last_seen" field.
func LastSeenNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldLastSeen))
}

// ExpiryEQ applies the EQ predicate on the "expiry" field.
func ExpiryEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldExpiry, v))
}

// ExpiryNEQ applies the NEQ predicate on the "expiry" field.
func ExpiryNEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldExpiry, v))
}

// ExpiryIn applies the In predicate on the "expiry" field.
func ExpiryIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldExpiry, vs...))
}

// ExpiryNotIn applies the NotIn predicate on the "expiry" field.
func ExpiryNotIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldExpiry, vs...))
}

// ExpiryGT applies the GT predicate on the "expiry" field.
func ExpiryGT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldExpiry, v))
}

// ExpiryGTE applies the GTE predicate on the "expiry" field.
func ExpiryGTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldExpiry, v))
}

// ExpiryLT applies the LT predicate on the "expiry" field.
func ExpiryLT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldExpiry, v))
}

// ExpiryLTE applies the LTE predicate on the "expiry" field.
func ExpiryLTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldExpiry, v))
}

// ExpiryIsNil applies the IsNil predicate on the "expiry" field.
func ExpiryIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldExpiry))
}

// ExpiryNotNil applies the NotNil predicate on the "expiry" field.
func ExpiryNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldExpiry))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldUpdatedAt, v))
}

// RegisterMethodEQ applies the EQ predicate on the "register_method" field.
func RegisterMethodEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldRegisterMethod, v))
}

// RegisterMethodNEQ applies the NEQ predicate on the "register_method" field.
func RegisterMethodNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldRegisterMethod, v))
}

// RegisterMethodIn applies the In predicate on the "register_method" field.
func RegisterMethodIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldRegisterMethod, vs...))
}

// RegisterMethodNotIn applies the NotIn predicate on the "register_method" field.
func RegisterMethodNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldRegisterMethod, vs...))
}

// RegisterMethodGT applies the GT predicate on the "register_method" field.
func RegisterMethodGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldRegisterMethod, v))
}

// RegisterMethodGTE applies the GTE predicate on the "register_method" field.
func RegisterMethodGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldRegisterMethod, v))
}

// RegisterMethodLT applies the LT predicate on the "register_method" field.
func RegisterMethodLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldRegisterMethod, v))
}

// RegisterMethodLTE applies the LTE predicate on the "register_method" field.
func RegisterMethodLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldRegisterMethod, v))
}

// RegisterMethodContains applies the Contains predicate on the "register_method" field.
func RegisterMethodContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldRegisterMethod, v))
}

// RegisterMethodHasPrefix applies the HasPrefix predicate on the "register_method" field.
func RegisterMethodHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldRegisterMethod, v))
}

// RegisterMethodHasSuffix applies the HasSuffix predicate on the "register_method" field.
func RegisterMethodHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldRegisterMethod, v))
}

// RegisterMethodEqualFold applies the EqualFold predicate on the "register_method" field.
func RegisterMethodEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldRegisterMethod, v))
}

// RegisterMethodContainsFold applies the ContainsFold predicate on the "register_method" field.
func RegisterMethodContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldRegisterMethod, v))
}

// ApprovedRoutesIsNil applies the IsNil predicate on the "approved_routes" field.
func ApprovedRoutesIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldApprovedRoutes))
}

// ApprovedRoutesNotNil applies the NotNil predicate on the "approved_routes" field.
func ApprovedRoutesNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldApprovedRoutes))
}

// AvailableRoutesIsNil applies the IsNil predicate on the "available_routes" field.
func AvailableRoutesIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldAvailableRoutes))
}

// AvailableRoutesNotNil applies the NotNil predicate on the "available_routes" field.
func AvailableRoutesNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldAvailableRoutes))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldTags))
}

// IsOnlineEQ applies the EQ predicate on the "is_online" field.
func IsOnlineEQ(v bool) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldIsOnline, v))
}

// IsOnlineNEQ applies the NEQ predicate on the "is_online" field.
func IsOnlineNEQ(v bool) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldIsOnline, v))
}

// IsOnlineIsNil applies the IsNil predicate on the "is_online" field.
func IsOnlineIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldIsOnline))
}

// IsOnlineNotNil applies the NotNil predicate on the "is_online" field.
func IsOnlineNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldIsOnline))
}

// EphemeralEQ applies the EQ predicate on the "ephemeral" field.
func EphemeralEQ(v bool) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldEphemeral, v))
}

// EphemeralNEQ applies the NEQ predicate on the "ephemeral" field.
func EphemeralNEQ(v bool) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldEphemeral, v))
}

// EphemeralIsNil applies the IsNil predicate on the "ephemeral" field.
func EphemeralIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldEphemeral))
}

// EphemeralNotNil applies the NotNil predicate on the "ephemeral" field.
func EphemeralNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldEphemeral))
}

// SessionEpochEQ applies the EQ predicate on the "session_epoch" field.
func SessionEpochEQ(v uint64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldSessionEpoch, v))
}

// SessionEpochNEQ applies the NEQ predicate on the "session_epoch" field.
func SessionEpochNEQ(v uint64) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldSessionEpoch, v))
}

// SessionEpochIn applies the In predicate on the "session_epoch" field.
func SessionEpochIn(vs ...uint64) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldSessionEpoch, vs...))
}

// SessionEpochNotIn applies the NotIn predicate on the "session_epoch" field.
func SessionEpochNotIn(vs ...uint64) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldSessionEpoch, vs...))
}

// SessionEpochGT applies the GT predicate on the "session_epoch" field.
func SessionEpochGT(v uint64) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldSessionEpoch, v))
}

// SessionEpochGTE applies the GTE predicate on the "session_epoch" field.
func SessionEpochGTE(v uint64) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldSessionEpoch, v))
}

// SessionEpochLT applies the LT predicate on the "session_epoch" field.
func SessionEpochLT(v uint64) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldSessionEpoch, v))
}

// SessionEpochLTE applies the LTE predicate on the "session_epoch" field.
func SessionEpochLTE(v uint64) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldSessionEpoch, v))
}

// SessionEpochIsNil applies the IsNil predicate on the "session_epoch" field.
func SessionEpochIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldSessionEpoch))
}

// SessionEpochNotNil applies the NotNil predicate on the "session_epoch" field.
func SessionEpochNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldSessionEpoch))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldNodeID, vs...))
}

// NodeIDGT applies the GT predicate on the "node_id" field.
func NodeIDGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldNodeID, v))
}

// NodeIDGTE applies the GTE predicate on the "node_id" field.
func NodeIDGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldNodeID, v))
}

// NodeIDLT applies the LT predicate on the "node_id" field.
func NodeIDLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldNodeID, v))
}

// NodeIDLTE applies the LTE predicate on the "node_id" field.
func NodeIDLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldNodeID, v))
}

// NodeIDContains applies the Contains predicate on the "node_id" field.
func NodeIDContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldNodeID, v))
}

// NodeIDHasPrefix applies the HasPrefix predicate on the "node_id" field.
func NodeIDHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldNodeID, v))
}

// NodeIDHasSuffix applies the HasSuffix predicate on the "node_id" field.
func NodeIDHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldNodeID, v))
}

// NodeIDIsNil applies the IsNil predicate on the "node_id" field.
func NodeIDIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldNodeID))
}

// NodeIDNotNil applies the NotNil predicate on the "node_id" field.
func NodeIDNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldNodeID))
}

// NodeIDEqualFold applies the EqualFold predicate on the "node_id" field.
func NodeIDEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldNodeID, v))
}

// NodeIDContainsFold applies the ContainsFold predicate on the "node_id" field.
func NodeIDContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldNodeID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldUserID))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPreAuthKey applies the HasEdge predicate on the "pre_auth_key" edge.
func HasPreAuthKey() predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PreAuthKeyTable, PreAuthKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPreAuthKeyWith applies the HasEdge predicate on the "pre_auth_key" edge with a given conditions (other predicates).
func HasPreAuthKeyWith(preds ...predicate.PreAuthKey) predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := newPreAuthKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Node) predicate.Node {
	return predicate.Node(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Node) predicate.Node {
	return predicate.Node(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Node) predicate.Node {
	return predicate.Node(sql.NotPredicates(p))
}
