// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ACLPoliciesColumns holds the columns for the "acl_policies" table.
	ACLPoliciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "default"},
		{Name: "policy", Type: field.TypeString, Size: 2147483647},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ACLPoliciesTable holds the schema information for the "acl_policies" table.
	ACLPoliciesTable = &schema.Table{
		Name:       "acl_policies",
		Columns:    ACLPoliciesColumns,
		PrimaryKey: []*schema.Column{ACLPoliciesColumns[0]},
	}
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "prefix", Type: field.TypeString, Unique: true},
		{Name: "key", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expiration", Type: field.TypeTime, Nullable: true},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
	}
	// NodesColumns holds the columns for the "nodes" table.
	NodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "machine_key", Type: field.TypeString, Unique: true},
		{Name: "node_key", Type: field.TypeString},
		{Name: "disco_key", Type: field.TypeString, Nullable: true},
		{Name: "endpoints", Type: field.TypeJSON, Nullable: true},
		{Name: "hostinfo", Type: field.TypeString, Nullable: true},
		{Name: "ip_addresses", Type: field.TypeJSON, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "given_name", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "last_seen", Type: field.TypeTime, Nullable: true},
		{Name: "expiry", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "register_method", Type: field.TypeString, Default: "unspecified"},
		{Name: "approved_routes", Type: field.TypeJSON, Nullable: true},
		{Name: "available_routes", Type: field.TypeJSON, Nullable: true},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "is_online", Type: field.TypeBool, Nullable: true, Default: false},
		{Name: "ephemeral", Type: field.TypeBool, Nullable: true, Default: false},
		{Name: "session_epoch", Type: field.TypeUint64, Nullable: true, Default: 0},
		{Name: "node_id", Type: field.TypeString, Nullable: true},
		{Name: "pre_auth_key_nodes", Type: field.TypeInt, Nullable: true},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
	}
	// NodesTable holds the schema information for the "nodes" table.
	NodesTable = &schema.Table{
		Name:       "nodes",
		Columns:    NodesColumns,
		PrimaryKey: []*schema.Column{NodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "nodes_pre_auth_keys_nodes",
				Columns:    []*schema.Column{NodesColumns[21]},
				RefColumns: []*schema.Column{PreAuthKeysColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "nodes_users_nodes",
				Columns:    []*schema.Column{NodesColumns[22]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "node_machine_key",
				Unique:  true,
				Columns: []*schema.Column{NodesColumns[1]},
			},
			{
				Name:    "node_node_key",
				Unique:  false,
				Columns: []*schema.Column{NodesColumns[2]},
			},
			{
				Name:    "node_given_name",
				Unique:  true,
				Columns: []*schema.Column{NodesColumns[8]},
			},
			{
				Name:    "node_name",
				Unique:  false,
				Columns: []*schema.Column{NodesColumns[7]},
			},
		},
	}
	// PreAuthKeysColumns holds the columns for the "pre_auth_keys" table.
	PreAuthKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "reusable", Type: field.TypeBool, Default: false},
		{Name: "ephemeral", Type: field.TypeBool, Default: false},
		{Name: "used_count", Type: field.TypeInt, Default: 0},
		{Name: "expiration", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "acl_tags", Type: field.TypeJSON, Nullable: true},
		{Name: "user_pre_auth_keys", Type: field.TypeInt, Nullable: true},
	}
	// PreAuthKeysTable holds the schema information for the "pre_auth_keys" table.
	PreAuthKeysTable = &schema.Table{
		Name:       "pre_auth_keys",
		Columns:    PreAuthKeysColumns,
		PrimaryKey: []*schema.Column{PreAuthKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pre_auth_keys_users_pre_auth_keys",
				Columns:    []*schema.Column{PreAuthKeysColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "display_name", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "profile_pic_url", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ACLPoliciesTable,
		APIKeysTable,
		NodesTable,
		PreAuthKeysTable,
		UsersTable,
	}
)

func init() {
	NodesTable.ForeignKeys[0].RefTable = PreAuthKeysTable
	NodesTable.ForeignKeys[1].RefTable = UsersTable
	PreAuthKeysTable.ForeignKeys[0].RefTable = UsersTable
}
