// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/juanfont/headscale-v2/ent/aclpolicy"
)

// ACLPolicy is the model entity for the ACLPolicy schema.
type ACLPolicy struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Policy holds the value of the "policy" field.
	Policy string `json:"policy,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ACLPolicy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aclpolicy.FieldID:
			values[i] = new(sql.NullInt64)
		case aclpolicy.FieldName, aclpolicy.FieldPolicy:
			values[i] = new(sql.NullString)
		case aclpolicy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ACLPolicy fields.
func (_m *ACLPolicy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aclpolicy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case aclpolicy.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case aclpolicy.FieldPolicy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field policy", values[i])
			} else if value.Valid {
				_m.Policy = value.String
			}
		case aclpolicy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ACLPolicy.
// This includes values selected through modifiers, order, etc.
func (_m *ACLPolicy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ACLPolicy.
// Note that you need to call ACLPolicy.Unwrap() before calling this method if this ACLPolicy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ACLPolicy) Update() *ACLPolicyUpdateOne {
	return NewACLPolicyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ACLPolicy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ACLPolicy) Unwrap() *ACLPolicy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ACLPolicy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ACLPolicy) String() string {
	var builder strings.Builder
	builder.WriteString("ACLPolicy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("policy=")
	builder.WriteString(_m.Policy)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ACLPolicies is a parsable slice of ACLPolicy.
type ACLPolicies []*ACLPolicy
