// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/juanfont/headscale-v2/ent/aclpolicy"
)

// ACLPolicyCreate is the builder for creating a ACLPolicy entity.
type ACLPolicyCreate struct {
	config
	mutation *ACLPolicyMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ACLPolicyCreate) SetName(v string) *ACLPolicyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *ACLPolicyCreate) SetNillableName(v *string) *ACLPolicyCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetPolicy sets the "policy" field.
func (_c *ACLPolicyCreate) SetPolicy(v string) *ACLPolicyCreate {
	_c.mutation.SetPolicy(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ACLPolicyCreate) SetUpdatedAt(v time.Time) *ACLPolicyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ACLPolicyCreate) SetNillableUpdatedAt(v *time.Time) *ACLPolicyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ACLPolicyMutation object of the builder.
func (_c *ACLPolicyCreate) Mutation() *ACLPolicyMutation {
	return _c.mutation
}

// Save creates the ACLPolicy in the database.
func (_c *ACLPolicyCreate) Save(ctx context.Context) (*ACLPolicy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ACLPolicyCreate) SaveX(ctx context.Context) *ACLPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ACLPolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ACLPolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ACLPolicyCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := aclpolicy.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := aclpolicy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ACLPolicyCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ACLPolicy.name"`)}
	}
	if _, ok := _c.mutation.Policy(); !ok {
		return &ValidationError{Name: "policy", err: errors.New(`ent: missing required field "ACLPolicy.policy"`)}
	}
	if v, ok := _c.mutation.Policy(); ok {
		if err := aclpolicy.PolicyValidator(v); err != nil {
			return &ValidationError{Name: "policy", err: fmt.Errorf(`ent: validator failed for field "ACLPolicy.policy": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ACLPolicy.updated_at"`)}
	}
	return nil
}

func (_c *ACLPolicyCreate) sqlSave(ctx context.Context) (*ACLPolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ACLPolicyCreate) createSpec() (*ACLPolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &ACLPolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(aclpolicy.Table, sqlgraph.NewFieldSpec(aclpolicy.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(aclpolicy.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Policy(); ok {
		_spec.SetField(aclpolicy.FieldPolicy, field.TypeString, value)
		_node.Policy = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(aclpolicy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ACLPolicyCreateBulk is the builder for creating many ACLPolicy entities in bulk.
type ACLPolicyCreateBulk struct {
	config
	err      error
	builders []*ACLPolicyCreate
}

// Save creates the ACLPolicy entities in the database.
func (_c *ACLPolicyCreateBulk) Save(ctx context.Context) ([]*ACLPolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ACLPolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ACLPolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ACLPolicyCreateBulk) SaveX(ctx context.Context) []*ACLPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ACLPolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ACLPolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
