// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/juanfont/headscale-v2/ent/aclpolicy"
	"github.com/juanfont/headscale-v2/ent/predicate"
)

// ACLPolicyUpdate is the builder for updating ACLPolicy entities.
type ACLPolicyUpdate struct {
	config
	hooks    []Hook
	mutation *ACLPolicyMutation
}

// Where appends a list predicates to the ACLPolicyUpdate builder.
func (_u *ACLPolicyUpdate) Where(ps ...predicate.ACLPolicy) *ACLPolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ACLPolicyUpdate) SetName(v string) *ACLPolicyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ACLPolicyUpdate) SetNillableName(v *string) *ACLPolicyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPolicy sets the "policy" field.
func (_u *ACLPolicyUpdate) SetPolicy(v string) *ACLPolicyUpdate {
	_u.mutation.SetPolicy(v)
	return _u
}

// SetNillablePolicy sets the "policy" field if the given value is not nil.
func (_u *ACLPolicyUpdate) SetNillablePolicy(v *string) *ACLPolicyUpdate {
	if v != nil {
		_u.SetPolicy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ACLPolicyUpdate) SetUpdatedAt(v time.Time) *ACLPolicyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ACLPolicyMutation object of the builder.
func (_u *ACLPolicyUpdate) Mutation() *ACLPolicyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ACLPolicyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ACLPolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ACLPolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ACLPolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ACLPolicyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aclpolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ACLPolicyUpdate) check() error {
	if v, ok := _u.mutation.Policy(); ok {
		if err := aclpolicy.PolicyValidator(v); err != nil {
			return &ValidationError{Name: "policy", err: fmt.Errorf(`ent: validator failed for field "ACLPolicy.policy": %w`, err)}
		}
	}
	return nil
}

func (_u *ACLPolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aclpolicy.Table, aclpolicy.Columns, sqlgraph.NewFieldSpec(aclpolicy.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(aclpolicy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Policy(); ok {
		_spec.SetField(aclpolicy.FieldPolicy, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aclpolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aclpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ACLPolicyUpdateOne is the builder for updating a single ACLPolicy entity.
type ACLPolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ACLPolicyMutation
}

// SetName sets the "name" field.
func (_u *ACLPolicyUpdateOne) SetName(v string) *ACLPolicyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ACLPolicyUpdateOne) SetNillableName(v *string) *ACLPolicyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPolicy sets the "policy" field.
func (_u *ACLPolicyUpdateOne) SetPolicy(v string) *ACLPolicyUpdateOne {
	_u.mutation.SetPolicy(v)
	return _u
}

// SetNillablePolicy sets the "policy" field if the given value is not nil.
func (_u *ACLPolicyUpdateOne) SetNillablePolicy(v *string) *ACLPolicyUpdateOne {
	if v != nil {
		_u.SetPolicy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ACLPolicyUpdateOne) SetUpdatedAt(v time.Time) *ACLPolicyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ACLPolicyMutation object of the builder.
func (_u *ACLPolicyUpdateOne) Mutation() *ACLPolicyMutation {
	return _u.mutation
}

// Where appends a list predicates to the ACLPolicyUpdate builder.
func (_u *ACLPolicyUpdateOne) Where(ps ...predicate.ACLPolicy) *ACLPolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ACLPolicyUpdateOne) Select(field string, fields ...string) *ACLPolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ACLPolicy entity.
func (_u *ACLPolicyUpdateOne) Save(ctx context.Context) (*ACLPolicy, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ACLPolicyUpdateOne) SaveX(ctx context.Context) *ACLPolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ACLPolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ACLPolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ACLPolicyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aclpolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ACLPolicyUpdateOne) check() error {
	if v, ok := _u.mutation.Policy(); ok {
		if err := aclpolicy.PolicyValidator(v); err != nil {
			return &ValidationError{Name: "policy", err: fmt.Errorf(`ent: validator failed for field "ACLPolicy.policy": %w`, err)}
		}
	}
	return nil
}

func (_u *ACLPolicyUpdateOne) sqlSave(ctx context.Context) (_node *ACLPolicy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aclpolicy.Table, aclpolicy.Columns, sqlgraph.NewFieldSpec(aclpolicy.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ACLPolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aclpolicy.FieldID)
		for _, f := range fields {
			if !aclpolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aclpolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(aclpolicy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Policy(); ok {
		_spec.SetField(aclpolicy.FieldPolicy, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aclpolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ACLPolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aclpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
