// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/juanfont/headscale-v2/ent/node"
	"github.com/juanfont/headscale-v2/ent/preauthkey"
	"github.com/juanfont/headscale-v2/ent/user"
)

// Node is the model entity for the Node schema.
type Node struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Node's MachineKey (v1)
	MachineKey string `json:"machine_key,omitempty"`
	// Node's current NodeKey
	NodeKey string `json:"node_key,omitempty"`
	// Node's current DiscoKey
	DiscoKey string `json:"disco_key,omitempty"`
	// Node's endpoints for direct connections
	Endpoints []string `json:"endpoints,omitempty"`
	// Node's Hostinfo JSON
	Hostinfo string `json:"hostinfo,omitempty"`
	// Node's allocated IP addresses
	IPAddresses []string `json:"ip_addresses,omitempty"`
	// Node's hostname from Hostinfo
	Name string `json:"name,omitempty"`
	// Node's assigned name
	GivenName string `json:"given_name,omitempty"`
	// Last time node was seen online
	LastSeen *time.Time `json:"last_seen,omitempty"`
	// Node's key expiry time
	Expiry *time.Time `json:"expiry,omitempty"`
	// Node registration time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Last update time
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// How the node was registered
	RegisterMethod string `json:"register_method,omitempty"`
	// Routes approved by policy
	ApprovedRoutes []string `json:"approved_routes,omitempty"`
	// Routes advertised by node
	AvailableRoutes []string `json:"available_routes,omitempty"`
	// Tags assigned to node
	Tags []string `json:"tags,omitempty"`
	// Node online status
	IsOnline bool `json:"is_online,omitempty"`
	// Whether node is ephemeral
	Ephemeral bool `json:"ephemeral,omitempty"`
	// Map session epoch
	SessionEpoch uint64 `json:"session_epoch,omitempty"`
	// Stable node ID
	NodeID string `json:"node_id,omitempty"`
	// Owner user ID
	UserID *int `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NodeQuery when eager-loading is set.
	Edges              NodeEdges `json:"edges"`
	pre_auth_key_nodes *int
	selectValues       sql.SelectValues
}

// NodeEdges holds the relations/edges for other nodes in the graph.
type NodeEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// PreAuthKey holds the value of the pre_auth_key edge.
	PreAuthKey *PreAuthKey `json:"pre_auth_key,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PreAuthKeyOrErr returns the PreAuthKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeEdges) PreAuthKeyOrErr() (*PreAuthKey, error) {
	if e.PreAuthKey != nil {
		return e.PreAuthKey, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: preauthkey.Label}
	}
	return nil, &NotLoadedError{edge: "pre_auth_key"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Node) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case node.FieldEndpoints, node.FieldIPAddresses, node.FieldApprovedRoutes, node.FieldAvailableRoutes, node.FieldTags:
			values[i] = new([]byte)
		case node.FieldIsOnline, node.FieldEphemeral:
			values[i] = new(sql.NullBool)
		case node.FieldID, node.FieldSessionEpoch, node.FieldUserID:
			values[i] = new(sql.NullInt64)
		case node.FieldMachineKey, node.FieldNodeKey, node.FieldDiscoKey, node.FieldHostinfo, node.FieldName, node.FieldGivenName, node.FieldRegisterMethod, node.FieldNodeID:
			values[i] = new(sql.NullString)
		case node.FieldLastSeen, node.FieldExpiry, node.FieldCreatedAt, node.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case node.ForeignKeys[0]: // pre_auth_key_nodes
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Node fields.
func (_m *Node) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case node.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case node.FieldMachineKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field machine_key", values[i])
			} else if value.Valid {
				_m.MachineKey = value.String
			}
		case node.FieldNodeKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_key", values[i])
			} else if value.Valid {
				_m.NodeKey = value.String
			}
		case node.FieldDiscoKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field disco_key", values[i])
			} else if value.Valid {
				_m.DiscoKey = value.String
			}
		case node.FieldEndpoints:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field endpoints", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Endpoints); err != nil {
					return fmt.Errorf("unmarshal field endpoints: %w", err)
				}
			}
		case node.FieldHostinfo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hostinfo", values[i])
			} else if value.Valid {
				_m.Hostinfo = value.String
			}
		case node.FieldIPAddresses:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field ip_addresses", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.IPAddresses); err != nil {
					return fmt.Errorf("unmarshal field ip_addresses: %w", err)
				}
			}
		case node.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case node.FieldGivenName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field given_name", values[i])
			} else if value.Valid {
				_m.GivenName = value.String
			}
		case node.FieldLastSeen:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen", values[i])
			} else if value.Valid {
				_m.LastSeen = new(time.Time)
				*_m.LastSeen = value.Time
			}
		case node.FieldExpiry:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expiry", values[i])
			} else if value.Valid {
				_m.Expiry = new(time.Time)
				*_m.Expiry = value.Time
			}
		case node.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case node.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case node.FieldRegisterMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field register_method", values[i])
			} else if value.Valid {
				_m.RegisterMethod = value.String
			}
		case node.FieldApprovedRoutes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field approved_routes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ApprovedRoutes); err != nil {
					return fmt.Errorf("unmarshal field approved_routes: %w", err)
				}
			}
		case node.FieldAvailableRoutes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field available_routes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AvailableRoutes); err != nil {
					return fmt.Errorf("unmarshal field available_routes: %w", err)
				}
			}
		case node.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case node.FieldIsOnline:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_online", values[i])
			} else if value.Valid {
				_m.IsOnline = value.Bool
			}
		case node.FieldEphemeral:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field ephemeral", values[i])
			} else if value.Valid {
				_m.Ephemeral = value.Bool
			}
		case node.FieldSessionEpoch:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field session_epoch", values[i])
			} else if value.Valid {
				_m.SessionEpoch = uint64(value.Int64)
			}
		case node.FieldNodeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_id", values[i])
			} else if value.Valid {
				_m.NodeID = value.String
			}
		case node.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(int)
				*_m.UserID = int(value.Int64)
			}
		case node.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field pre_auth_key_nodes", value)
			} else if value.Valid {
				_m.pre_auth_key_nodes = new(int)
				*_m.pre_auth_key_nodes = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Node.
// This includes values selected through modifiers, order, etc.
func (_m *Node) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Node entity.
func (_m *Node) QueryUser() *UserQuery {
	return NewNodeClient(_m.config).QueryUser(_m)
}

// QueryPreAuthKey queries the "pre_auth_key" edge of the Node entity.
func (_m *Node) QueryPreAuthKey() *PreAuthKeyQuery {
	return NewNodeClient(_m.config).QueryPreAuthKey(_m)
}

// Update returns a builder for updating this Node.
// Note that you need to call Node.Unwrap() before calling this method if this Node
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Node) Update() *NodeUpdateOne {
	return NewNodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Node entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Node) Unwrap() *Node {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Node is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Node) String() string {
	var builder strings.Builder
	builder.WriteString("Node(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("machine_key=")
	builder.WriteString(_m.MachineKey)
	builder.WriteString(", ")
	builder.WriteString("node_key=")
	builder.WriteString(_m.NodeKey)
	builder.WriteString(", ")
	builder.WriteString("disco_key=")
	builder.WriteString(_m.DiscoKey)
	builder.WriteString(", ")
	builder.WriteString("endpoints=")
	builder.WriteString(fmt.Sprintf("%v", _m.Endpoints))
	builder.WriteString(", ")
	builder.WriteString("hostinfo=")
	builder.WriteString(_m.Hostinfo)
	builder.WriteString(", ")
	builder.WriteString("ip_addresses=")
	builder.WriteString(fmt.Sprintf("%v", _m.IPAddresses))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("given_name=")
	builder.WriteString(_m.GivenName)
	builder.WriteString(", ")
	if v := _m.LastSeen; v != nil {
		builder.WriteString("last_seen=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Expiry; v != nil {
		builder.WriteString("expiry=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("register_method=")
	builder.WriteString(_m.RegisterMethod)
	builder.WriteString(", ")
	builder.WriteString("approved_routes=")
	builder.WriteString(fmt.Sprintf("%v", _m.ApprovedRoutes))
	builder.WriteString(", ")
	builder.WriteString("available_routes=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvailableRoutes))
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteString(", ")
	builder.WriteString("is_online=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsOnline))
	builder.WriteString(", ")
	builder.WriteString("ephemeral=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ephemeral))
	builder.WriteString(", ")
	builder.WriteString("session_epoch=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionEpoch))
	builder.WriteString(", ")
	builder.WriteString("node_id=")
	builder.WriteString(_m.NodeID)
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Nodes is a parsable slice of Node.
type Nodes []*Node
