// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/juanfont/headscale-v2/ent/node"
	"github.com/juanfont/headscale-v2/ent/preauthkey"
	"github.com/juanfont/headscale-v2/ent/user"
)

// NodeCreate is the builder for creating a Node entity.
type NodeCreate struct {
	config
	mutation *NodeMutation
	hooks    []Hook
}

// SetMachineKey sets the "machine_key" field.
func (_c *NodeCreate) SetMachineKey(v string) *NodeCreate {
	_c.mutation.SetMachineKey(v)
	return _c
}

// SetNodeKey sets the "node_key" field.
func (_c *NodeCreate) SetNodeKey(v string) *NodeCreate {
	_c.mutation.SetNodeKey(v)
	return _c
}

// SetDiscoKey sets the "disco_key" field.
func (_c *NodeCreate) SetDiscoKey(v string) *NodeCreate {
	_c.mutation.SetDiscoKey(v)
	return _c
}

// SetNillableDiscoKey sets the "disco_key" field if the given value is not nil.
func (_c *NodeCreate) SetNillableDiscoKey(v *string) *NodeCreate {
	if v != nil {
		_c.SetDiscoKey(*v)
	}
	return _c
}

// SetEndpoints sets the "endpoints" field.
func (_c *NodeCreate) SetEndpoints(v []string) *NodeCreate {
	_c.mutation.SetEndpoints(v)
	return _c
}

// SetHostinfo sets the "hostinfo" field.
func (_c *NodeCreate) SetHostinfo(v string) *NodeCreate {
	_c.mutation.SetHostinfo(v)
	return _c
}

// SetNillableHostinfo sets the "hostinfo" field if the given value is not nil.
func (_c *NodeCreate) SetNillableHostinfo(v *string) *NodeCreate {
	if v != nil {
		_c.SetHostinfo(*v)
	}
	return _c
}

// SetIPAddresses sets the "ip_addresses" field.
func (_c *NodeCreate) SetIPAddresses(v []string) *NodeCreate {
	_c.mutation.SetIPAddresses(v)
	return _c
}

// SetName sets the "name" field.
func (_c *NodeCreate) SetName(v string) *NodeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetGivenName sets the "given_name" field.
func (_c *NodeCreate) SetGivenName(v string) *NodeCreate {
	_c.mutation.SetGivenName(v)
	return _c
}

// SetNillableGivenName sets the "given_name" field if the given value is not nil.
func (_c *NodeCreate) SetNillableGivenName(v *string) *NodeCreate {
	if v != nil {
		_c.SetGivenName(*v)
	}
	return _c
}

// SetLastSeen sets the "last_seen" field.
func (_c *NodeCreate) SetLastSeen(v time.Time) *NodeCreate {
	_c.mutation.SetLastSeen(v)
	return _c
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_c *NodeCreate) SetNillableLastSeen(v *time.Time) *NodeCreate {
	if v != nil {
		_c.SetLastSeen(*v)
	}
	return _c
}

// SetExpiry sets the "expiry" field.
func (_c *NodeCreate) SetExpiry(v time.Time) *NodeCreate {
	_c.mutation.SetExpiry(v)
	return _c
}

// SetNillableExpiry sets the "expiry" field if the given value is not nil.
func (_c *NodeCreate) SetNillableExpiry(v *time.Time) *NodeCreate {
	if v != nil {
		_c.SetExpiry(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NodeCreate) SetCreatedAt(v time.Time) *NodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NodeCreate) SetNillableCreatedAt(v *time.Time) *NodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NodeCreate) SetUpdatedAt(v time.Time) *NodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NodeCreate) SetNillableUpdatedAt(v *time.Time) *NodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRegisterMethod sets the "register_method" field.
func (_c *NodeCreate) SetRegisterMethod(v string) *NodeCreate {
	_c.mutation.SetRegisterMethod(v)
	return _c
}

// SetNillableRegisterMethod sets the "register_method" field if the given value is not nil.
func (_c *NodeCreate) SetNillableRegisterMethod(v *string) *NodeCreate {
	if v != nil {
		_c.SetRegisterMethod(*v)
	}
	return _c
}

// SetApprovedRoutes sets the "approved_routes" field.
func (_c *NodeCreate) SetApprovedRoutes(v []string) *NodeCreate {
	_c.mutation.SetApprovedRoutes(v)
	return _c
}

// SetAvailableRoutes sets the "available_routes" field.
func (_c *NodeCreate) SetAvailableRoutes(v []string) *NodeCreate {
	_c.mutation.SetAvailableRoutes(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *NodeCreate) SetTags(v []string) *NodeCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetIsOnline sets the "is_online" field.
func (_c *NodeCreate) SetIsOnline(v bool) *NodeCreate {
	_c.mutation.SetIsOnline(v)
	return _c
}

// SetNillableIsOnline sets the "is_online" field if the given value is not nil.
func (_c *NodeCreate) SetNillableIsOnline(v *bool) *NodeCreate {
	if v != nil {
		_c.SetIsOnline(*v)
	}
	return _c
}

// SetEphemeral sets the "ephemeral" field.
func (_c *NodeCreate) SetEphemeral(v bool) *NodeCreate {
	_c.mutation.SetEphemeral(v)
	return _c
}

// SetNillableEphemeral sets the "ephemeral" field if the given value is not nil.
func (_c *NodeCreate) SetNillableEphemeral(v *bool) *NodeCreate {
	if v != nil {
		_c.SetEphemeral(*v)
	}
	return _c
}

// SetSessionEpoch sets the "session_epoch" field.
func (_c *NodeCreate) SetSessionEpoch(v uint64) *NodeCreate {
	_c.mutation.SetSessionEpoch(v)
	return _c
}

// SetNillableSessionEpoch sets the "session_epoch" field if the given value is not nil.
func (_c *NodeCreate) SetNillableSessionEpoch(v *uint64) *NodeCreate {
	if v != nil {
		_c.SetSessionEpoch(*v)
	}
	return _c
}

// SetNodeID sets the "node_id" field.
func (_c *NodeCreate) SetNodeID(v string) *NodeCreate {
	_c.mutation.SetNodeID(v)
	return _c
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_c *NodeCreate) SetNillableNodeID(v *string) *NodeCreate {
	if v != nil {
		_c.SetNodeID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *NodeCreate) SetUserID(v int) *NodeCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *NodeCreate) SetNillableUserID(v *int) *NodeCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *NodeCreate) SetUser(v *User) *NodeCreate {
	return _c.SetUserID(v.ID)
}

// SetPreAuthKeyID sets the "pre_auth_key" edge to the PreAuthKey entity by ID.
func (_c *NodeCreate) SetPreAuthKeyID(id int) *NodeCreate {
	_c.mutation.SetPreAuthKeyID(id)
	return _c
}

// SetNillablePreAuthKeyID sets the "pre_auth_key" edge to the PreAuthKey entity by ID if the given value is not nil.
func (_c *NodeCreate) SetNillablePreAuthKeyID(id *int) *NodeCreate {
	if id != nil {
		_c = _c.SetPreAuthKeyID(*id)
	}
	return _c
}

// SetPreAuthKey sets the "pre_auth_key" edge to the PreAuthKey entity.
func (_c *NodeCreate) SetPreAuthKey(v *PreAuthKey) *NodeCreate {
	return _c.SetPreAuthKeyID(v.ID)
}

// Mutation returns the NodeMutation object of the builder.
func (_c *NodeCreate) Mutation() *NodeMutation {
	return _c.mutation
}

// Save creates the Node in the database.
func (_c *NodeCreate) Save(ctx context.Context) (*Node, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NodeCreate) SaveX(ctx context.Context) *Node {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NodeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := node.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := node.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.RegisterMethod(); !ok {
		v := node.DefaultRegisterMethod
		_c.mutation.SetRegisterMethod(v)
	}
	if _, ok := _c.mutation.IsOnline(); !ok {
		v := node.DefaultIsOnline
		_c.mutation.SetIsOnline(v)
	}
	if _, ok := _c.mutation.Ephemeral(); !ok {
		v := node.DefaultEphemeral
		_c.mutation.SetEphemeral(v)
	}
	if _, ok := _c.mutation.SessionEpoch(); !ok {
		v := node.DefaultSessionEpoch
		_c.mutation.SetSessionEpoch(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NodeCreate) check() error {
	if _, ok := _c.mutation.MachineKey(); !ok {
		return &ValidationError{Name: "machine_key", err: errors.New(`ent: missing required field "Node.machine_key"`)}
	}
	if v, ok := _c.mutation.MachineKey(); ok {
		if err := node.MachineKeyValidator(v); err != nil {
			return &ValidationError{Name: "machine_key", err: fmt.Errorf(`ent: validator failed for field "Node.machine_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NodeKey(); !ok {
		return &ValidationError{Name: "node_key", err: errors.New(`ent: missing required field "Node.node_key"`)}
	}
	if v, ok := _c.mutation.NodeKey(); ok {
		if err := node.NodeKeyValidator(v); err != nil {
			return &ValidationError{Name: "node_key", err: fmt.Errorf(`ent: validator failed for field "Node.node_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Node.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := node.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Node.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Node.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Node.updated_at"`)}
	}
	if _, ok := _c.mutation.RegisterMethod(); !ok {
		return &ValidationError{Name: "register_method", err: errors.New(`ent: missing required field "Node.register_method"`)}
	}
	return nil
}

func (_c *NodeCreate) sqlSave(ctx context.Context) (*Node, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NodeCreate) createSpec() (*Node, *sqlgraph.CreateSpec) {
	var (
		_node = &Node{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(node.Table, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.MachineKey(); ok {
		_spec.SetField(node.FieldMachineKey, field.TypeString, value)
		_node.MachineKey = value
	}
	if value, ok := _c.mutation.NodeKey(); ok {
		_spec.SetField(node.FieldNodeKey, field.TypeString, value)
		_node.NodeKey = value
	}
	if value, ok := _c.mutation.DiscoKey(); ok {
		_spec.SetField(node.FieldDiscoKey, field.TypeString, value)
		_node.DiscoKey = value
	}
	if value, ok := _c.mutation.Endpoints(); ok {
		_spec.SetField(node.FieldEndpoints, field.TypeJSON, value)
		_node.Endpoints = value
	}
	if value, ok := _c.mutation.Hostinfo(); ok {
		_spec.SetField(node.FieldHostinfo, field.TypeString, value)
		_node.Hostinfo = value
	}
	if value, ok := _c.mutation.IPAddresses(); ok {
		_spec.SetField(node.FieldIPAddresses, field.TypeJSON, value)
		_node.IPAddresses = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(node.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GivenName(); ok {
		_spec.SetField(node.FieldGivenName, field.TypeString, value)
		_node.GivenName = value
	}
	if value, ok := _c.mutation.LastSeen(); ok {
		_spec.SetField(node.FieldLastSeen, field.TypeTime, value)
		_node.LastSeen = &value
	}
	if value, ok := _c.mutation.Expiry(); ok {
		_spec.SetField(node.FieldExpiry, field.TypeTime, value)
		_node.Expiry = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(node.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.RegisterMethod(); ok {
		_spec.SetField(node.FieldRegisterMethod, field.TypeString, value)
		_node.RegisterMethod = value
	}
	if value, ok := _c.mutation.ApprovedRoutes(); ok {
		_spec.SetField(node.FieldApprovedRoutes, field.TypeJSON, value)
		_node.ApprovedRoutes = value
	}
	if value, ok := _c.mutation.AvailableRoutes(); ok {
		_spec.SetField(node.FieldAvailableRoutes, field.TypeJSON, value)
		_node.AvailableRoutes = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(node.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.IsOnline(); ok {
		_spec.SetField(node.FieldIsOnline, field.TypeBool, value)
		_node.IsOnline = value
	}
	if value, ok := _c.mutation.Ephemeral(); ok {
		_spec.SetField(node.FieldEphemeral, field.TypeBool, value)
		_node.Ephemeral = value
	}
	if value, ok := _c.mutation.SessionEpoch(); ok {
		_spec.SetField(node.FieldSessionEpoch, field.TypeUint64, value)
		_node.SessionEpoch = value
	}
	if value, ok := _c.mutation.NodeID(); ok {
		_spec.SetField(node.FieldNodeID, field.TypeString, value)
		_node.NodeID = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.UserTable,
			Columns: []string{node.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PreAuthKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.PreAuthKeyTable,
			Columns: []string{node.PreAuthKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(preauthkey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.pre_auth_key_nodes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NodeCreateBulk is the builder for creating many Node entities in bulk.
type NodeCreateBulk struct {
	config
	err      error
	builders []*NodeCreate
}

// Save creates the Node entities in the database.
func (_c *NodeCreateBulk) Save(ctx context.Context) ([]*Node, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Node, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NodeCreateBulk) SaveX(ctx context.Context) []*Node {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
