// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/juanfont/headscale-v2/ent/node"
	"github.com/juanfont/headscale-v2/ent/preauthkey"
	"github.com/juanfont/headscale-v2/ent/predicate"
	"github.com/juanfont/headscale-v2/ent/user"
)

// NodeUpdate is the builder for updating Node entities.
type NodeUpdate struct {
	config
	hooks    []Hook
	mutation *NodeMutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdate) Where(ps ...predicate.Node) *NodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMachineKey sets the "machine_key" field.
func (_u *NodeUpdate) SetMachineKey(v string) *NodeUpdate {
	_u.mutation.SetMachineKey(v)
	return _u
}

// SetNillableMachineKey sets the "machine_key" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableMachineKey(v *string) *NodeUpdate {
	if v != nil {
		_u.SetMachineKey(*v)
	}
	return _u
}

// SetNodeKey sets the "node_key" field.
func (_u *NodeUpdate) SetNodeKey(v string) *NodeUpdate {
	_u.mutation.SetNodeKey(v)
	return _u
}

// SetNillableNodeKey sets the "node_key" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableNodeKey(v *string) *NodeUpdate {
	if v != nil {
		_u.SetNodeKey(*v)
	}
	return _u
}

// SetDiscoKey sets the "disco_key" field.
func (_u *NodeUpdate) SetDiscoKey(v string) *NodeUpdate {
	_u.mutation.SetDiscoKey(v)
	return _u
}

// SetNillableDiscoKey sets the "disco_key" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableDiscoKey(v *string) *NodeUpdate {
	if v != nil {
		_u.SetDiscoKey(*v)
	}
	return _u
}

// ClearDiscoKey clears the value of the "disco_key" field.
func (_u *NodeUpdate) ClearDiscoKey() *NodeUpdate {
	_u.mutation.ClearDiscoKey()
	return _u
}

// SetEndpoints sets the "endpoints" field.
func (_u *NodeUpdate) SetEndpoints(v []string) *NodeUpdate {
	_u.mutation.SetEndpoints(v)
	return _u
}

// AppendEndpoints appends value to the "endpoints" field.
func (_u *NodeUpdate) AppendEndpoints(v []string) *NodeUpdate {
	_u.mutation.AppendEndpoints(v)
	return _u
}

// ClearEndpoints clears the value of the "endpoints" field.
func (_u *NodeUpdate) ClearEndpoints() *NodeUpdate {
	_u.mutation.ClearEndpoints()
	return _u
}

// SetHostinfo sets the "hostinfo" field.
func (_u *NodeUpdate) SetHostinfo(v string) *NodeUpdate {
	_u.mutation.SetHostinfo(v)
	return _u
}

// SetNillableHostinfo sets the "hostinfo" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableHostinfo(v *string) *NodeUpdate {
	if v != nil {
		_u.SetHostinfo(*v)
	}
	return _u
}

// ClearHostinfo clears the value of the "hostinfo" field.
func (_u *NodeUpdate) ClearHostinfo() *NodeUpdate {
	_u.mutation.ClearHostinfo()
	return _u
}

// SetIPAddresses sets the "ip_addresses" field.
func (_u *NodeUpdate) SetIPAddresses(v []string) *NodeUpdate {
	_u.mutation.SetIPAddresses(v)
	return _u
}

// AppendIPAddresses appends value to the "ip_addresses" field.
func (_u *NodeUpdate) AppendIPAddresses(v []string) *NodeUpdate {
	_u.mutation.AppendIPAddresses(v)
	return _u
}

// ClearIPAddresses clears the value of the "ip_addresses" field.
func (_u *NodeUpdate) ClearIPAddresses() *NodeUpdate {
	_u.mutation.ClearIPAddresses()
	return _u
}

// SetName sets the "name" field.
func (_u *NodeUpdate) SetName(v string) *NodeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableName(v *string) *NodeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGivenName sets the "given_name" field.
func (_u *NodeUpdate) SetGivenName(v string) *NodeUpdate {
	_u.mutation.SetGivenName(v)
	return _u
}

// SetNillableGivenName sets the "given_name" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableGivenName(v *string) *NodeUpdate {
	if v != nil {
		_u.SetGivenName(*v)
	}
	return _u
}

// ClearGivenName clears the value of the "given_name" field.
func (_u *NodeUpdate) ClearGivenName() *NodeUpdate {
	_u.mutation.ClearGivenName()
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *NodeUpdate) SetLastSeen(v time.Time) *NodeUpdate {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableLastSeen(v *time.Time) *NodeUpdate {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// ClearLastSeen clears the value of the "last_seen" field.
func (_u *NodeUpdate) ClearLastSeen() *NodeUpdate {
	_u.mutation.ClearLastSeen()
	return _u
}

// SetExpiry sets the "expiry" field.
func (_u *NodeUpdate) SetExpiry(v time.Time) *NodeUpdate {
	_u.mutation.SetExpiry(v)
	return _u
}

// SetNillableExpiry sets the "expiry" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableExpiry(v *time.Time) *NodeUpdate {
	if v != nil {
		_u.SetExpiry(*v)
	}
	return _u
}

// ClearExpiry clears the value of the "expiry" field.
func (_u *NodeUpdate) ClearExpiry() *NodeUpdate {
	_u.mutation.ClearExpiry()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NodeUpdate) SetCreatedAt(v time.Time) *NodeUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableCreatedAt(v *time.Time) *NodeUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeUpdate) SetUpdatedAt(v time.Time) *NodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRegisterMethod sets the "register_method" field.
func (_u *NodeUpdate) SetRegisterMethod(v string) *NodeUpdate {
	_u.mutation.SetRegisterMethod(v)
	return _u
}

// SetNillableRegisterMethod sets the "register_method" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableRegisterMethod(v *string) *NodeUpdate {
	if v != nil {
		_u.SetRegisterMethod(*v)
	}
	return _u
}

// SetApprovedRoutes sets the "approved_routes" field.
func (_u *NodeUpdate) SetApprovedRoutes(v []string) *NodeUpdate {
	_u.mutation.SetApprovedRoutes(v)
	return _u
}

// AppendApprovedRoutes appends value to the "approved_routes" field.
func (_u *NodeUpdate) AppendApprovedRoutes(v []string) *NodeUpdate {
	_u.mutation.AppendApprovedRoutes(v)
	return _u
}

// ClearApprovedRoutes clears the value of the "approved_routes" field.
func (_u *NodeUpdate) ClearApprovedRoutes() *NodeUpdate {
	_u.mutation.ClearApprovedRoutes()
	return _u
}

// SetAvailableRoutes sets the "available_routes" field.
func (_u *NodeUpdate) SetAvailableRoutes(v []string) *NodeUpdate {
	_u.mutation.SetAvailableRoutes(v)
	return _u
}

// AppendAvailableRoutes appends value to the "available_routes" field.
func (_u *NodeUpdate) AppendAvailableRoutes(v []string) *NodeUpdate {
	_u.mutation.AppendAvailableRoutes(v)
	return _u
}

// ClearAvailableRoutes clears the value of the "available_routes" field.
func (_u *NodeUpdate) ClearAvailableRoutes() *NodeUpdate {
	_u.mutation.ClearAvailableRoutes()
	return _u
}

// SetTags sets the "tags" field.
func (_u *NodeUpdate) SetTags(v []string) *NodeUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *NodeUpdate) AppendTags(v []string) *NodeUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *NodeUpdate) ClearTags() *NodeUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetIsOnline sets the "is_online" field.
func (_u *NodeUpdate) SetIsOnline(v bool) *NodeUpdate {
	_u.mutation.SetIsOnline(v)
	return _u
}

// SetNillableIsOnline sets the "is_online" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableIsOnline(v *bool) *NodeUpdate {
	if v != nil {
		_u.SetIsOnline(*v)
	}
	return _u
}

// ClearIsOnline clears the value of the "is_online" field.
func (_u *NodeUpdate) ClearIsOnline() *NodeUpdate {
	_u.mutation.ClearIsOnline()
	return _u
}

// SetEphemeral sets the "ephemeral" field.
func (_u *NodeUpdate) SetEphemeral(v bool) *NodeUpdate {
	_u.mutation.SetEphemeral(v)
	return _u
}

// SetNillableEphemeral sets the "ephemeral" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableEphemeral(v *bool) *NodeUpdate {
	if v != nil {
		_u.SetEphemeral(*v)
	}
	return _u
}

// ClearEphemeral clears the value of the "ephemeral" field.
func (_u *NodeUpdate) ClearEphemeral() *NodeUpdate {
	_u.mutation.ClearEphemeral()
	return _u
}

// SetSessionEpoch sets the "session_epoch" field.
func (_u *NodeUpdate) SetSessionEpoch(v uint64) *NodeUpdate {
	_u.mutation.ResetSessionEpoch()
	_u.mutation.SetSessionEpoch(v)
	return _u
}

// SetNillableSessionEpoch sets the "session_epoch" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableSessionEpoch(v *uint64) *NodeUpdate {
	if v != nil {
		_u.SetSessionEpoch(*v)
	}
	return _u
}

// AddSessionEpoch adds value to the "session_epoch" field.
func (_u *NodeUpdate) AddSessionEpoch(v int64) *NodeUpdate {
	_u.mutation.AddSessionEpoch(v)
	return _u
}

// ClearSessionEpoch clears the value of the "session_epoch" field.
func (_u *NodeUpdate) ClearSessionEpoch() *NodeUpdate {
	_u.mutation.ClearSessionEpoch()
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *NodeUpdate) SetNodeID(v string) *NodeUpdate {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableNodeID(v *string) *NodeUpdate {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// ClearNodeID clears the value of the "node_id" field.
func (_u *NodeUpdate) ClearNodeID() *NodeUpdate {
	_u.mutation.ClearNodeID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *NodeUpdate) SetUserID(v int) *NodeUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableUserID(v *int) *NodeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *NodeUpdate) ClearUserID() *NodeUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *NodeUpdate) SetUser(v *User) *NodeUpdate {
	return _u.SetUserID(v.ID)
}

// SetPreAuthKeyID sets the "pre_auth_key" edge to the PreAuthKey entity by ID.
func (_u *NodeUpdate) SetPreAuthKeyID(id int) *NodeUpdate {
	_u.mutation.SetPreAuthKeyID(id)
	return _u
}

// SetNillablePreAuthKeyID sets the "pre_auth_key" edge to the PreAuthKey entity by ID if the given value is not nil.
func (_u *NodeUpdate) SetNillablePreAuthKeyID(id *int) *NodeUpdate {
	if id != nil {
		_u = _u.SetPreAuthKeyID(*id)
	}
	return _u
}

// SetPreAuthKey sets the "pre_auth_key" edge to the PreAuthKey entity.
func (_u *NodeUpdate) SetPreAuthKey(v *PreAuthKey) *NodeUpdate {
	return _u.SetPreAuthKeyID(v.ID)
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdate) Mutation() *NodeMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *NodeUpdate) ClearUser() *NodeUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearPreAuthKey clears the "pre_auth_key" edge to the PreAuthKey entity.
func (_u *NodeUpdate) ClearPreAuthKey() *NodeUpdate {
	_u.mutation.ClearPreAuthKey()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := node.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdate) check() error {
	if v, ok := _u.mutation.MachineKey(); ok {
		if err := node.MachineKeyValidator(v); err != nil {
			return &ValidationError{Name: "machine_key", err: fmt.Errorf(`ent: validator failed for field "Node.machine_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NodeKey(); ok {
		if err := node.NodeKeyValidator(v); err != nil {
			return &ValidationError{Name: "node_key", err: fmt.Errorf(`ent: validator failed for field "Node.node_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := node.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Node.name": %w`, err)}
		}
	}
	return nil
}

func (_u *NodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MachineKey(); ok {
		_spec.SetField(node.FieldMachineKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeKey(); ok {
		_spec.SetField(node.FieldNodeKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DiscoKey(); ok {
		_spec.SetField(node.FieldDiscoKey, field.TypeString, value)
	}
	if _u.mutation.DiscoKeyCleared() {
		_spec.ClearField(node.FieldDiscoKey, field.TypeString)
	}
	if value, ok := _u.mutation.Endpoints(); ok {
		_spec.SetField(node.FieldEndpoints, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEndpoints(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldEndpoints, value)
		})
	}
	if _u.mutation.EndpointsCleared() {
		_spec.ClearField(node.FieldEndpoints, field.TypeJSON)
	}
	if value, ok := _u.mutation.Hostinfo(); ok {
		_spec.SetField(node.FieldHostinfo, field.TypeString, value)
	}
	if _u.mutation.HostinfoCleared() {
		_spec.ClearField(node.FieldHostinfo, field.TypeString)
	}
	if value, ok := _u.mutation.IPAddresses(); ok {
		_spec.SetField(node.FieldIPAddresses, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIPAddresses(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldIPAddresses, value)
		})
	}
	if _u.mutation.IPAddressesCleared() {
		_spec.ClearField(node.FieldIPAddresses, field.TypeJSON)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(node.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GivenName(); ok {
		_spec.SetField(node.FieldGivenName, field.TypeString, value)
	}
	if _u.mutation.GivenNameCleared() {
		_spec.ClearField(node.FieldGivenName, field.TypeString)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(node.FieldLastSeen, field.TypeTime, value)
	}
	if _u.mutation.LastSeenCleared() {
		_spec.ClearField(node.FieldLastSeen, field.TypeTime)
	}
	if value, ok := _u.mutation.Expiry(); ok {
		_spec.SetField(node.FieldExpiry, field.TypeTime, value)
	}
	if _u.mutation.ExpiryCleared() {
		_spec.ClearField(node.FieldExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(node.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RegisterMethod(); ok {
		_spec.SetField(node.FieldRegisterMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedRoutes(); ok {
		_spec.SetField(node.FieldApprovedRoutes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedApprovedRoutes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldApprovedRoutes, value)
		})
	}
	if _u.mutation.ApprovedRoutesCleared() {
		_spec.ClearField(node.FieldApprovedRoutes, field.TypeJSON)
	}
	if value, ok := _u.mutation.AvailableRoutes(); ok {
		_spec.SetField(node.FieldAvailableRoutes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAvailableRoutes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldAvailableRoutes, value)
		})
	}
	if _u.mutation.AvailableRoutesCleared() {
		_spec.ClearField(node.FieldAvailableRoutes, field.TypeJSON)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(node.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(node.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsOnline(); ok {
		_spec.SetField(node.FieldIsOnline, field.TypeBool, value)
	}
	if _u.mutation.IsOnlineCleared() {
		_spec.ClearField(node.FieldIsOnline, field.TypeBool)
	}
	if value, ok := _u.mutation.Ephemeral(); ok {
		_spec.SetField(node.FieldEphemeral, field.TypeBool, value)
	}
	if _u.mutation.EphemeralCleared() {
		_spec.ClearField(node.FieldEphemeral, field.TypeBool)
	}
	if value, ok := _u.mutation.SessionEpoch(); ok {
		_spec.SetField(node.FieldSessionEpoch, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedSessionEpoch(); ok {
		_spec.AddField(node.FieldSessionEpoch, field.TypeUint64, value)
	}
	if _u.mutation.SessionEpochCleared() {
		_spec.ClearField(node.FieldSessionEpoch, field.TypeUint64)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(node.FieldNodeID, field.TypeString, value)
	}
	if _u.mutation.NodeIDCleared() {
		_spec.ClearField(node.FieldNodeID, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.UserTable,
			Columns: []string{node.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.UserTable,
			Columns: []string{node.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PreAuthKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.PreAuthKeyTable,
			Columns: []string{node.PreAuthKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(preauthkey.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PreAuthKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.PreAuthKeyTable,
			Columns: []string{node.PreAuthKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(preauthkey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NodeUpdateOne is the builder for updating a single Node entity.
type NodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeMutation
}

// SetMachineKey sets the "machine_key" field.
func (_u *NodeUpdateOne) SetMachineKey(v string) *NodeUpdateOne {
	_u.mutation.SetMachineKey(v)
	return _u
}

// SetNillableMachineKey sets the "machine_key" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableMachineKey(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetMachineKey(*v)
	}
	return _u
}

// SetNodeKey sets the "node_key" field.
func (_u *NodeUpdateOne) SetNodeKey(v string) *NodeUpdateOne {
	_u.mutation.SetNodeKey(v)
	return _u
}

// SetNillableNodeKey sets the "node_key" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableNodeKey(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetNodeKey(*v)
	}
	return _u
}

// SetDiscoKey sets the "disco_key" field.
func (_u *NodeUpdateOne) SetDiscoKey(v string) *NodeUpdateOne {
	_u.mutation.SetDiscoKey(v)
	return _u
}

// SetNillableDiscoKey sets the "disco_key" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableDiscoKey(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetDiscoKey(*v)
	}
	return _u
}

// ClearDiscoKey clears the value of the "disco_key" field.
func (_u *NodeUpdateOne) ClearDiscoKey() *NodeUpdateOne {
	_u.mutation.ClearDiscoKey()
	return _u
}

// SetEndpoints sets the "endpoints" field.
func (_u *NodeUpdateOne) SetEndpoints(v []string) *NodeUpdateOne {
	_u.mutation.SetEndpoints(v)
	return _u
}

// AppendEndpoints appends value to the "endpoints" field.
func (_u *NodeUpdateOne) AppendEndpoints(v []string) *NodeUpdateOne {
	_u.mutation.AppendEndpoints(v)
	return _u
}

// ClearEndpoints clears the value of the "endpoints" field.
func (_u *NodeUpdateOne) ClearEndpoints() *NodeUpdateOne {
	_u.mutation.ClearEndpoints()
	return _u
}

// SetHostinfo sets the "hostinfo" field.
func (_u *NodeUpdateOne) SetHostinfo(v string) *NodeUpdateOne {
	_u.mutation.SetHostinfo(v)
	return _u
}

// SetNillableHostinfo sets the "hostinfo" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableHostinfo(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetHostinfo(*v)
	}
	return _u
}

// ClearHostinfo clears the value of the "hostinfo" field.
func (_u *NodeUpdateOne) ClearHostinfo() *NodeUpdateOne {
	_u.mutation.ClearHostinfo()
	return _u
}

// SetIPAddresses sets the "ip_addresses" field.
func (_u *NodeUpdateOne) SetIPAddresses(v []string) *NodeUpdateOne {
	_u.mutation.SetIPAddresses(v)
	return _u
}

// AppendIPAddresses appends value to the "ip_addresses" field.
func (_u *NodeUpdateOne) AppendIPAddresses(v []string) *NodeUpdateOne {
	_u.mutation.AppendIPAddresses(v)
	return _u
}

// ClearIPAddresses clears the value of the "ip_addresses" field.
func (_u *NodeUpdateOne) ClearIPAddresses() *NodeUpdateOne {
	_u.mutation.ClearIPAddresses()
	return _u
}

// SetName sets the "name" field.
func (_u *NodeUpdateOne) SetName(v string) *NodeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableName(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGivenName sets the "given_name" field.
func (_u *NodeUpdateOne) SetGivenName(v string) *NodeUpdateOne {
	_u.mutation.SetGivenName(v)
	return _u
}

// SetNillableGivenName sets the "given_name" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableGivenName(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetGivenName(*v)
	}
	return _u
}

// ClearGivenName clears the value of the "given_name" field.
func (_u *NodeUpdateOne) ClearGivenName() *NodeUpdateOne {
	_u.mutation.ClearGivenName()
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *NodeUpdateOne) SetLastSeen(v time.Time) *NodeUpdateOne {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableLastSeen(v *time.Time) *NodeUpdateOne {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// ClearLastSeen clears the value of the "last_seen" field.
func (_u *NodeUpdateOne) ClearLastSeen() *NodeUpdateOne {
	_u.mutation.ClearLastSeen()
	return _u
}

// SetExpiry sets the "expiry" field.
func (_u *NodeUpdateOne) SetExpiry(v time.Time) *NodeUpdateOne {
	_u.mutation.SetExpiry(v)
	return _u
}

// SetNillableExpiry sets the "expiry" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableExpiry(v *time.Time) *NodeUpdateOne {
	if v != nil {
		_u.SetExpiry(*v)
	}
	return _u
}

// ClearExpiry clears the value of the "expiry" field.
func (_u *NodeUpdateOne) ClearExpiry() *NodeUpdateOne {
	_u.mutation.ClearExpiry()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NodeUpdateOne) SetCreatedAt(v time.Time) *NodeUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableCreatedAt(v *time.Time) *NodeUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeUpdateOne) SetUpdatedAt(v time.Time) *NodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRegisterMethod sets the "register_method" field.
func (_u *NodeUpdateOne) SetRegisterMethod(v string) *NodeUpdateOne {
	_u.mutation.SetRegisterMethod(v)
	return _u
}

// SetNillableRegisterMethod sets the "register_method" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableRegisterMethod(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetRegisterMethod(*v)
	}
	return _u
}

// SetApprovedRoutes sets the "approved_routes" field.
func (_u *NodeUpdateOne) SetApprovedRoutes(v []string) *NodeUpdateOne {
	_u.mutation.SetApprovedRoutes(v)
	return _u
}

// AppendApprovedRoutes appends value to the "approved_routes" field.
func (_u *NodeUpdateOne) AppendApprovedRoutes(v []string) *NodeUpdateOne {
	_u.mutation.AppendApprovedRoutes(v)
	return _u
}

// ClearApprovedRoutes clears the value of the "approved_routes" field.
func (_u *NodeUpdateOne) ClearApprovedRoutes() *NodeUpdateOne {
	_u.mutation.ClearApprovedRoutes()
	return _u
}

// SetAvailableRoutes sets the "available_routes" field.
func (_u *NodeUpdateOne) SetAvailableRoutes(v []string) *NodeUpdateOne {
	_u.mutation.SetAvailableRoutes(v)
	return _u
}

// AppendAvailableRoutes appends value to the "available_routes" field.
func (_u *NodeUpdateOne) AppendAvailableRoutes(v []string) *NodeUpdateOne {
	_u.mutation.AppendAvailableRoutes(v)
	return _u
}

// ClearAvailableRoutes clears the value of the "available_routes" field.
func (_u *NodeUpdateOne) ClearAvailableRoutes() *NodeUpdateOne {
	_u.mutation.ClearAvailableRoutes()
	return _u
}

// SetTags sets the "tags" field.
func (_u *NodeUpdateOne) SetTags(v []string) *NodeUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *NodeUpdateOne) AppendTags(v []string) *NodeUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *NodeUpdateOne) ClearTags() *NodeUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetIsOnline sets the "is_online" field.
func (_u *NodeUpdateOne) SetIsOnline(v bool) *NodeUpdateOne {
	_u.mutation.SetIsOnline(v)
	return _u
}

// SetNillableIsOnline sets the "is_online" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableIsOnline(v *bool) *NodeUpdateOne {
	if v != nil {
		_u.SetIsOnline(*v)
	}
	return _u
}

// ClearIsOnline clears the value of the "is_online" field.
func (_u *NodeUpdateOne) ClearIsOnline() *NodeUpdateOne {
	_u.mutation.ClearIsOnline()
	return _u
}

// SetEphemeral sets the "ephemeral" field.
func (_u *NodeUpdateOne) SetEphemeral(v bool) *NodeUpdateOne {
	_u.mutation.SetEphemeral(v)
	return _u
}

// SetNillableEphemeral sets the "ephemeral" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableEphemeral(v *bool) *NodeUpdateOne {
	if v != nil {
		_u.SetEphemeral(*v)
	}
	return _u
}

// ClearEphemeral clears the value of the "ephemeral" field.
func (_u *NodeUpdateOne) ClearEphemeral() *NodeUpdateOne {
	_u.mutation.ClearEphemeral()
	return _u
}

// SetSessionEpoch sets the "session_epoch" field.
func (_u *NodeUpdateOne) SetSessionEpoch(v uint64) *NodeUpdateOne {
	_u.mutation.ResetSessionEpoch()
	_u.mutation.SetSessionEpoch(v)
	return _u
}

// SetNillableSessionEpoch sets the "session_epoch" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableSessionEpoch(v *uint64) *NodeUpdateOne {
	if v != nil {
		_u.SetSessionEpoch(*v)
	}
	return _u
}

// AddSessionEpoch adds value to the "session_epoch" field.
func (_u *NodeUpdateOne) AddSessionEpoch(v int64) *NodeUpdateOne {
	_u.mutation.AddSessionEpoch(v)
	return _u
}

// ClearSessionEpoch clears the value of the "session_epoch" field.
func (_u *NodeUpdateOne) ClearSessionEpoch() *NodeUpdateOne {
	_u.mutation.ClearSessionEpoch()
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *NodeUpdateOne) SetNodeID(v string) *NodeUpdateOne {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableNodeID(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// ClearNodeID clears the value of the "node_id" field.
func (_u *NodeUpdateOne) ClearNodeID() *NodeUpdateOne {
	_u.mutation.ClearNodeID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *NodeUpdateOne) SetUserID(v int) *NodeUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableUserID(v *int) *NodeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *NodeUpdateOne) ClearUserID() *NodeUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *NodeUpdateOne) SetUser(v *User) *NodeUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetPreAuthKeyID sets the "pre_auth_key" edge to the PreAuthKey entity by ID.
func (_u *NodeUpdateOne) SetPreAuthKeyID(id int) *NodeUpdateOne {
	_u.mutation.SetPreAuthKeyID(id)
	return _u
}

// SetNillablePreAuthKeyID sets the "pre_auth_key" edge to the PreAuthKey entity by ID if the given value is not nil.
func (_u *NodeUpdateOne) SetNillablePreAuthKeyID(id *int) *NodeUpdateOne {
	if id != nil {
		_u = _u.SetPreAuthKeyID(*id)
	}
	return _u
}

// SetPreAuthKey sets the "pre_auth_key" edge to the PreAuthKey entity.
func (_u *NodeUpdateOne) SetPreAuthKey(v *PreAuthKey) *NodeUpdateOne {
	return _u.SetPreAuthKeyID(v.ID)
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdateOne) Mutation() *NodeMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *NodeUpdateOne) ClearUser() *NodeUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearPreAuthKey clears the "pre_auth_key" edge to the PreAuthKey entity.
func (_u *NodeUpdateOne) ClearPreAuthKey() *NodeUpdateOne {
	_u.mutation.ClearPreAuthKey()
	return _u
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdateOne) Where(ps ...predicate.Node) *NodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NodeUpdateOne) Select(field string, fields ...string) *NodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Node entity.
func (_u *NodeUpdateOne) Save(ctx context.Context) (*Node, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdateOne) SaveX(ctx context.Context) *Node {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := node.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdateOne) check() error {
	if v, ok := _u.mutation.MachineKey(); ok {
		if err := node.MachineKeyValidator(v); err != nil {
			return &ValidationError{Name: "machine_key", err: fmt.Errorf(`ent: validator failed for field "Node.machine_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NodeKey(); ok {
		if err := node.NodeKeyValidator(v); err != nil {
			return &ValidationError{Name: "node_key", err: fmt.Errorf(`ent: validator failed for field "Node.node_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := node.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Node.name": %w`, err)}
		}
	}
	return nil
}

func (_u *NodeUpdateOne) sqlSave(ctx context.Context) (_node *Node, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Node.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, node.FieldID)
		for _, f := range fields {
			if !node.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != node.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MachineKey(); ok {
		_spec.SetField(node.FieldMachineKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeKey(); ok {
		_spec.SetField(node.FieldNodeKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DiscoKey(); ok {
		_spec.SetField(node.FieldDiscoKey, field.TypeString, value)
	}
	if _u.mutation.DiscoKeyCleared() {
		_spec.ClearField(node.FieldDiscoKey, field.TypeString)
	}
	if value, ok := _u.mutation.Endpoints(); ok {
		_spec.SetField(node.FieldEndpoints, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEndpoints(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldEndpoints, value)
		})
	}
	if _u.mutation.EndpointsCleared() {
		_spec.ClearField(node.FieldEndpoints, field.TypeJSON)
	}
	if value, ok := _u.mutation.Hostinfo(); ok {
		_spec.SetField(node.FieldHostinfo, field.TypeString, value)
	}
	if _u.mutation.HostinfoCleared() {
		_spec.ClearField(node.FieldHostinfo, field.TypeString)
	}
	if value, ok := _u.mutation.IPAddresses(); ok {
		_spec.SetField(node.FieldIPAddresses, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIPAddresses(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldIPAddresses, value)
		})
	}
	if _u.mutation.IPAddressesCleared() {
		_spec.ClearField(node.FieldIPAddresses, field.TypeJSON)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(node.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GivenName(); ok {
		_spec.SetField(node.FieldGivenName, field.TypeString, value)
	}
	if _u.mutation.GivenNameCleared() {
		_spec.ClearField(node.FieldGivenName, field.TypeString)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(node.FieldLastSeen, field.TypeTime, value)
	}
	if _u.mutation.LastSeenCleared() {
		_spec.ClearField(node.FieldLastSeen, field.TypeTime)
	}
	if value, ok := _u.mutation.Expiry(); ok {
		_spec.SetField(node.FieldExpiry, field.TypeTime, value)
	}
	if _u.mutation.ExpiryCleared() {
		_spec.ClearField(node.FieldExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(node.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RegisterMethod(); ok {
		_spec.SetField(node.FieldRegisterMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedRoutes(); ok {
		_spec.SetField(node.FieldApprovedRoutes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedApprovedRoutes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldApprovedRoutes, value)
		})
	}
	if _u.mutation.ApprovedRoutesCleared() {
		_spec.ClearField(node.FieldApprovedRoutes, field.TypeJSON)
	}
	if value, ok := _u.mutation.AvailableRoutes(); ok {
		_spec.SetField(node.FieldAvailableRoutes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAvailableRoutes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldAvailableRoutes, value)
		})
	}
	if _u.mutation.AvailableRoutesCleared() {
		_spec.ClearField(node.FieldAvailableRoutes, field.TypeJSON)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(node.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(node.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsOnline(); ok {
		_spec.SetField(node.FieldIsOnline, field.TypeBool, value)
	}
	if _u.mutation.IsOnlineCleared() {
		_spec.ClearField(node.FieldIsOnline, field.TypeBool)
	}
	if value, ok := _u.mutation.Ephemeral(); ok {
		_spec.SetField(node.FieldEphemeral, field.TypeBool, value)
	}
	if _u.mutation.EphemeralCleared() {
		_spec.ClearField(node.FieldEphemeral, field.TypeBool)
	}
	if value, ok := _u.mutation.SessionEpoch(); ok {
		_spec.SetField(node.FieldSessionEpoch, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedSessionEpoch(); ok {
		_spec.AddField(node.FieldSessionEpoch, field.TypeUint64, value)
	}
	if _u.mutation.SessionEpochCleared() {
		_spec.ClearField(node.FieldSessionEpoch, field.TypeUint64)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(node.FieldNodeID, field.TypeString, value)
	}
	if _u.mutation.NodeIDCleared() {
		_spec.ClearField(node.FieldNodeID, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.UserTable,
			Columns: []string{node.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.UserTable,
			Columns: []string{node.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PreAuthKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.PreAuthKeyTable,
			Columns: []string{node.PreAuthKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(preauthkey.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PreAuthKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.PreAuthKeyTable,
			Columns: []string{node.PreAuthKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(preauthkey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Node{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
