// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/juanfont/headscale-v2/ent/node"
	"github.com/juanfont/headscale-v2/ent/preauthkey"
	"github.com/juanfont/headscale-v2/ent/user"
)

// PreAuthKeyCreate is the builder for creating a PreAuthKey entity.
type PreAuthKeyCreate struct {
	config
	mutation *PreAuthKeyMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *PreAuthKeyCreate) SetKey(v string) *PreAuthKeyCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetReusable sets the "reusable" field.
func (_c *PreAuthKeyCreate) SetReusable(v bool) *PreAuthKeyCreate {
	_c.mutation.SetReusable(v)
	return _c
}

// SetNillableReusable sets the "reusable" field if the given value is not nil.
func (_c *PreAuthKeyCreate) SetNillableReusable(v *bool) *PreAuthKeyCreate {
	if v != nil {
		_c.SetReusable(*v)
	}
	return _c
}

// SetEphemeral sets the "ephemeral" field.
func (_c *PreAuthKeyCreate) SetEphemeral(v bool) *PreAuthKeyCreate {
	_c.mutation.SetEphemeral(v)
	return _c
}

// SetNillableEphemeral sets the "ephemeral" field if the given value is not nil.
func (_c *PreAuthKeyCreate) SetNillableEphemeral(v *bool) *PreAuthKeyCreate {
	if v != nil {
		_c.SetEphemeral(*v)
	}
	return _c
}

// SetUsedCount sets the "used_count" field.
func (_c *PreAuthKeyCreate) SetUsedCount(v int) *PreAuthKeyCreate {
	_c.mutation.SetUsedCount(v)
	return _c
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_c *PreAuthKeyCreate) SetNillableUsedCount(v *int) *PreAuthKeyCreate {
	if v != nil {
		_c.SetUsedCount(*v)
	}
	return _c
}

// SetExpiration sets the "expiration" field.
func (_c *PreAuthKeyCreate) SetExpiration(v time.Time) *PreAuthKeyCreate {
	_c.mutation.SetExpiration(v)
	return _c
}

// SetNillableExpiration sets the "expiration" field if the given value is not nil.
func (_c *PreAuthKeyCreate) SetNillableExpiration(v *time.Time) *PreAuthKeyCreate {
	if v != nil {
		_c.SetExpiration(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PreAuthKeyCreate) SetCreatedAt(v time.Time) *PreAuthKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PreAuthKeyCreate) SetNillableCreatedAt(v *time.Time) *PreAuthKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetACLTags sets the "acl_tags" field.
func (_c *PreAuthKeyCreate) SetACLTags(v []string) *PreAuthKeyCreate {
	_c.mutation.SetACLTags(v)
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *PreAuthKeyCreate) SetUserID(id int) *PreAuthKeyCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_c *PreAuthKeyCreate) SetNillableUserID(id *int) *PreAuthKeyCreate {
	if id != nil {
		_c = _c.SetUserID(*id)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PreAuthKeyCreate) SetUser(v *User) *PreAuthKeyCreate {
	return _c.SetUserID(v.ID)
}

// AddNodeIDs adds the "nodes" edge to the Node entity by IDs.
func (_c *PreAuthKeyCreate) AddNodeIDs(ids ...int) *PreAuthKeyCreate {
	_c.mutation.AddNodeIDs(ids...)
	return _c
}

// AddNodes adds the "nodes" edges to the Node entity.
func (_c *PreAuthKeyCreate) AddNodes(v ...*Node) *PreAuthKeyCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNodeIDs(ids...)
}

// Mutation returns the PreAuthKeyMutation object of the builder.
func (_c *PreAuthKeyCreate) Mutation() *PreAuthKeyMutation {
	return _c.mutation
}

// Save creates the PreAuthKey in the database.
func (_c *PreAuthKeyCreate) Save(ctx context.Context) (*PreAuthKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PreAuthKeyCreate) SaveX(ctx context.Context) *PreAuthKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PreAuthKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PreAuthKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PreAuthKeyCreate) defaults() {
	if _, ok := _c.mutation.Reusable(); !ok {
		v := preauthkey.DefaultReusable
		_c.mutation.SetReusable(v)
	}
	if _, ok := _c.mutation.Ephemeral(); !ok {
		v := preauthkey.DefaultEphemeral
		_c.mutation.SetEphemeral(v)
	}
	if _, ok := _c.mutation.UsedCount(); !ok {
		v := preauthkey.DefaultUsedCount
		_c.mutation.SetUsedCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := preauthkey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PreAuthKeyCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "PreAuthKey.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := preauthkey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "PreAuthKey.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Reusable(); !ok {
		return &ValidationError{Name: "reusable", err: errors.New(`ent: missing required field "PreAuthKey.reusable"`)}
	}
	if _, ok := _c.mutation.Ephemeral(); !ok {
		return &ValidationError{Name: "ephemeral", err: errors.New(`ent: missing required field "PreAuthKey.ephemeral"`)}
	}
	if _, ok := _c.mutation.UsedCount(); !ok {
		return &ValidationError{Name: "used_count", err: errors.New(`ent: missing required field "PreAuthKey.used_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PreAuthKey.created_at"`)}
	}
	return nil
}

func (_c *PreAuthKeyCreate) sqlSave(ctx context.Context) (*PreAuthKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PreAuthKeyCreate) createSpec() (*PreAuthKey, *sqlgraph.CreateSpec) {
	var (
		_node = &PreAuthKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(preauthkey.Table, sqlgraph.NewFieldSpec(preauthkey.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(preauthkey.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Reusable(); ok {
		_spec.SetField(preauthkey.FieldReusable, field.TypeBool, value)
		_node.Reusable = value
	}
	if value, ok := _c.mutation.Ephemeral(); ok {
		_spec.SetField(preauthkey.FieldEphemeral, field.TypeBool, value)
		_node.Ephemeral = value
	}
	if value, ok := _c.mutation.UsedCount(); ok {
		_spec.SetField(preauthkey.FieldUsedCount, field.TypeInt, value)
		_node.UsedCount = value
	}
	if value, ok := _c.mutation.Expiration(); ok {
		_spec.SetField(preauthkey.FieldExpiration, field.TypeTime, value)
		_node.Expiration = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(preauthkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ACLTags(); ok {
		_spec.SetField(preauthkey.FieldACLTags, field.TypeJSON, value)
		_node.ACLTags = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   preauthkey.UserTable,
			Columns: []string{preauthkey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_pre_auth_keys = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   preauthkey.NodesTable,
			Columns: []string{preauthkey.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PreAuthKeyCreateBulk is the builder for creating many PreAuthKey entities in bulk.
type PreAuthKeyCreateBulk struct {
	config
	err      error
	builders []*PreAuthKeyCreate
}

// Save creates the PreAuthKey entities in the database.
func (_c *PreAuthKeyCreateBulk) Save(ctx context.Context) ([]*PreAuthKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PreAuthKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PreAuthKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PreAuthKeyCreateBulk) SaveX(ctx context.Context) []*PreAuthKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PreAuthKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PreAuthKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
