// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/juanfont/headscale-v2/ent/node"
	"github.com/juanfont/headscale-v2/ent/preauthkey"
	"github.com/juanfont/headscale-v2/ent/predicate"
	"github.com/juanfont/headscale-v2/ent/user"
)

// PreAuthKeyUpdate is the builder for updating PreAuthKey entities.
type PreAuthKeyUpdate struct {
	config
	hooks    []Hook
	mutation *PreAuthKeyMutation
}

// Where appends a list predicates to the PreAuthKeyUpdate builder.
func (_u *PreAuthKeyUpdate) Where(ps ...predicate.PreAuthKey) *PreAuthKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *PreAuthKeyUpdate) SetKey(v string) *PreAuthKeyUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *PreAuthKeyUpdate) SetNillableKey(v *string) *PreAuthKeyUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetReusable sets the "reusable" field.
func (_u *PreAuthKeyUpdate) SetReusable(v bool) *PreAuthKeyUpdate {
	_u.mutation.SetReusable(v)
	return _u
}

// SetNillableReusable sets the "reusable" field if the given value is not nil.
func (_u *PreAuthKeyUpdate) SetNillableReusable(v *bool) *PreAuthKeyUpdate {
	if v != nil {
		_u.SetReusable(*v)
	}
	return _u
}

// SetEphemeral sets the "ephemeral" field.
func (_u *PreAuthKeyUpdate) SetEphemeral(v bool) *PreAuthKeyUpdate {
	_u.mutation.SetEphemeral(v)
	return _u
}

// SetNillableEphemeral sets the "ephemeral" field if the given value is not nil.
func (_u *PreAuthKeyUpdate) SetNillableEphemeral(v *bool) *PreAuthKeyUpdate {
	if v != nil {
		_u.SetEphemeral(*v)
	}
	return _u
}

// SetUsedCount sets the "used_count" field.
func (_u *PreAuthKeyUpdate) SetUsedCount(v int) *PreAuthKeyUpdate {
	_u.mutation.ResetUsedCount()
	_u.mutation.SetUsedCount(v)
	return _u
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_u *PreAuthKeyUpdate) SetNillableUsedCount(v *int) *PreAuthKeyUpdate {
	if v != nil {
		_u.SetUsedCount(*v)
	}
	return _u
}

// AddUsedCount adds value to the "used_count" field.
func (_u *PreAuthKeyUpdate) AddUsedCount(v int) *PreAuthKeyUpdate {
	_u.mutation.AddUsedCount(v)
	return _u
}

// SetExpiration sets the "expiration" field.
func (_u *PreAuthKeyUpdate) SetExpiration(v time.Time) *PreAuthKeyUpdate {
	_u.mutation.SetExpiration(v)
	return _u
}

// SetNillableExpiration sets the "expiration" field if the given value is not nil.
func (_u *PreAuthKeyUpdate) SetNillableExpiration(v *time.Time) *PreAuthKeyUpdate {
	if v != nil {
		_u.SetExpiration(*v)
	}
	return _u
}

// ClearExpiration clears the value of the "expiration" field.
func (_u *PreAuthKeyUpdate) ClearExpiration() *PreAuthKeyUpdate {
	_u.mutation.ClearExpiration()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PreAuthKeyUpdate) SetCreatedAt(v time.Time) *PreAuthKeyUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PreAuthKeyUpdate) SetNillableCreatedAt(v *time.Time) *PreAuthKeyUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetACLTags sets the "acl_tags" field.
func (_u *PreAuthKeyUpdate) SetACLTags(v []string) *PreAuthKeyUpdate {
	_u.mutation.SetACLTags(v)
	return _u
}

// AppendACLTags appends value to the "acl_tags" field.
func (_u *PreAuthKeyUpdate) AppendACLTags(v []string) *PreAuthKeyUpdate {
	_u.mutation.AppendACLTags(v)
	return _u
}

// ClearACLTags clears the value of the "acl_tags" field.
func (_u *PreAuthKeyUpdate) ClearACLTags() *PreAuthKeyUpdate {
	_u.mutation.ClearACLTags()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *PreAuthKeyUpdate) SetUserID(id int) *PreAuthKeyUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *PreAuthKeyUpdate) SetNillableUserID(id *int) *PreAuthKeyUpdate {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PreAuthKeyUpdate) SetUser(v *User) *PreAuthKeyUpdate {
	return _u.SetUserID(v.ID)
}

// AddNodeIDs adds the "nodes" edge to the Node entity by IDs.
func (_u *PreAuthKeyUpdate) AddNodeIDs(ids ...int) *PreAuthKeyUpdate {
	_u.mutation.AddNodeIDs(ids...)
	return _u
}

// AddNodes adds the "nodes" edges to the Node entity.
func (_u *PreAuthKeyUpdate) AddNodes(v ...*Node) *PreAuthKeyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNodeIDs(ids...)
}

// Mutation returns the PreAuthKeyMutation object of the builder.
func (_u *PreAuthKeyUpdate) Mutation() *PreAuthKeyMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PreAuthKeyUpdate) ClearUser() *PreAuthKeyUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearNodes clears all "nodes" edges to the Node entity.
func (_u *PreAuthKeyUpdate) ClearNodes() *PreAuthKeyUpdate {
	_u.mutation.ClearNodes()
	return _u
}

// RemoveNodeIDs removes the "nodes" edge to Node entities by IDs.
func (_u *PreAuthKeyUpdate) RemoveNodeIDs(ids ...int) *PreAuthKeyUpdate {
	_u.mutation.RemoveNodeIDs(ids...)
	return _u
}

// RemoveNodes removes "nodes" edges to Node entities.
func (_u *PreAuthKeyUpdate) RemoveNodes(v ...*Node) *PreAuthKeyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNodeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PreAuthKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PreAuthKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PreAuthKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PreAuthKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PreAuthKeyUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := preauthkey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "PreAuthKey.key": %w`, err)}
		}
	}
	return nil
}

func (_u *PreAuthKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(preauthkey.Table, preauthkey.Columns, sqlgraph.NewFieldSpec(preauthkey.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(preauthkey.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reusable(); ok {
		_spec.SetField(preauthkey.FieldReusable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Ephemeral(); ok {
		_spec.SetField(preauthkey.FieldEphemeral, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UsedCount(); ok {
		_spec.SetField(preauthkey.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedCount(); ok {
		_spec.AddField(preauthkey.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Expiration(); ok {
		_spec.SetField(preauthkey.FieldExpiration, field.TypeTime, value)
	}
	if _u.mutation.ExpirationCleared() {
		_spec.ClearField(preauthkey.FieldExpiration, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(preauthkey.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ACLTags(); ok {
		_spec.SetField(preauthkey.FieldACLTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedACLTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, preauthkey.FieldACLTags, value)
		})
	}
	if _u.mutation.ACLTagsCleared() {
		_spec.ClearField(preauthkey.FieldACLTags, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   preauthkey.UserTable,
			Columns: []string{preauthkey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   preauthkey.UserTable,
			Columns: []string{preauthkey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   preauthkey.NodesTable,
			Columns: []string{preauthkey.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNodesIDs(); len(nodes) > 0 && !_u.mutation.NodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   preauthkey.NodesTable,
			Columns: []string{preauthkey.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   preauthkey.NodesTable,
			Columns: []string{preauthkey.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{preauthkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PreAuthKeyUpdateOne is the builder for updating a single PreAuthKey entity.
type PreAuthKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PreAuthKeyMutation
}

// SetKey sets the "key" field.
func (_u *PreAuthKeyUpdateOne) SetKey(v string) *PreAuthKeyUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *PreAuthKeyUpdateOne) SetNillableKey(v *string) *PreAuthKeyUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetReusable sets the "reusable" field.
func (_u *PreAuthKeyUpdateOne) SetReusable(v bool) *PreAuthKeyUpdateOne {
	_u.mutation.SetReusable(v)
	return _u
}

// SetNillableReusable sets the "reusable" field if the given value is not nil.
func (_u *PreAuthKeyUpdateOne) SetNillableReusable(v *bool) *PreAuthKeyUpdateOne {
	if v != nil {
		_u.SetReusable(*v)
	}
	return _u
}

// SetEphemeral sets the "ephemeral" field.
func (_u *PreAuthKeyUpdateOne) SetEphemeral(v bool) *PreAuthKeyUpdateOne {
	_u.mutation.SetEphemeral(v)
	return _u
}

// SetNillableEphemeral sets the "ephemeral" field if the given value is not nil.
func (_u *PreAuthKeyUpdateOne) SetNillableEphemeral(v *bool) *PreAuthKeyUpdateOne {
	if v != nil {
		_u.SetEphemeral(*v)
	}
	return _u
}

// SetUsedCount sets the "used_count" field.
func (_u *PreAuthKeyUpdateOne) SetUsedCount(v int) *PreAuthKeyUpdateOne {
	_u.mutation.ResetUsedCount()
	_u.mutation.SetUsedCount(v)
	return _u
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_u *PreAuthKeyUpdateOne) SetNillableUsedCount(v *int) *PreAuthKeyUpdateOne {
	if v != nil {
		_u.SetUsedCount(*v)
	}
	return _u
}

// AddUsedCount adds value to the "used_count" field.
func (_u *PreAuthKeyUpdateOne) AddUsedCount(v int) *PreAuthKeyUpdateOne {
	_u.mutation.AddUsedCount(v)
	return _u
}

// SetExpiration sets the "expiration" field.
func (_u *PreAuthKeyUpdateOne) SetExpiration(v time.Time) *PreAuthKeyUpdateOne {
	_u.mutation.SetExpiration(v)
	return _u
}

// SetNillableExpiration sets the "expiration" field if the given value is not nil.
func (_u *PreAuthKeyUpdateOne) SetNillableExpiration(v *time.Time) *PreAuthKeyUpdateOne {
	if v != nil {
		_u.SetExpiration(*v)
	}
	return _u
}

// ClearExpiration clears the value of the "expiration" field.
func (_u *PreAuthKeyUpdateOne) ClearExpiration() *PreAuthKeyUpdateOne {
	_u.mutation.ClearExpiration()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PreAuthKeyUpdateOne) SetCreatedAt(v time.Time) *PreAuthKeyUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PreAuthKeyUpdateOne) SetNillableCreatedAt(v *time.Time) *PreAuthKeyUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetACLTags sets the "acl_tags" field.
func (_u *PreAuthKeyUpdateOne) SetACLTags(v []string) *PreAuthKeyUpdateOne {
	_u.mutation.SetACLTags(v)
	return _u
}

// AppendACLTags appends value to the "acl_tags" field.
func (_u *PreAuthKeyUpdateOne) AppendACLTags(v []string) *PreAuthKeyUpdateOne {
	_u.mutation.AppendACLTags(v)
	return _u
}

// ClearACLTags clears the value of the "acl_tags" field.
func (_u *PreAuthKeyUpdateOne) ClearACLTags() *PreAuthKeyUpdateOne {
	_u.mutation.ClearACLTags()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *PreAuthKeyUpdateOne) SetUserID(id int) *PreAuthKeyUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *PreAuthKeyUpdateOne) SetNillableUserID(id *int) *PreAuthKeyUpdateOne {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PreAuthKeyUpdateOne) SetUser(v *User) *PreAuthKeyUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddNodeIDs adds the "nodes" edge to the Node entity by IDs.
func (_u *PreAuthKeyUpdateOne) AddNodeIDs(ids ...int) *PreAuthKeyUpdateOne {
	_u.mutation.AddNodeIDs(ids...)
	return _u
}

// AddNodes adds the "nodes" edges to the Node entity.
func (_u *PreAuthKeyUpdateOne) AddNodes(v ...*Node) *PreAuthKeyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNodeIDs(ids...)
}

// Mutation returns the PreAuthKeyMutation object of the builder.
func (_u *PreAuthKeyUpdateOne) Mutation() *PreAuthKeyMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PreAuthKeyUpdateOne) ClearUser() *PreAuthKeyUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearNodes clears all "nodes" edges to the Node entity.
func (_u *PreAuthKeyUpdateOne) ClearNodes() *PreAuthKeyUpdateOne {
	_u.mutation.ClearNodes()
	return _u
}

// RemoveNodeIDs removes the "nodes" edge to Node entities by IDs.
func (_u *PreAuthKeyUpdateOne) RemoveNodeIDs(ids ...int) *PreAuthKeyUpdateOne {
	_u.mutation.RemoveNodeIDs(ids...)
	return _u
}

// RemoveNodes removes "nodes" edges to Node entities.
func (_u *PreAuthKeyUpdateOne) RemoveNodes(v ...*Node) *PreAuthKeyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNodeIDs(ids...)
}

// Where appends a list predicates to the PreAuthKeyUpdate builder.
func (_u *PreAuthKeyUpdateOne) Where(ps ...predicate.PreAuthKey) *PreAuthKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PreAuthKeyUpdateOne) Select(field string, fields ...string) *PreAuthKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PreAuthKey entity.
func (_u *PreAuthKeyUpdateOne) Save(ctx context.Context) (*PreAuthKey, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PreAuthKeyUpdateOne) SaveX(ctx context.Context) *PreAuthKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PreAuthKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PreAuthKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PreAuthKeyUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := preauthkey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "PreAuthKey.key": %w`, err)}
		}
	}
	return nil
}

func (_u *PreAuthKeyUpdateOne) sqlSave(ctx context.Context) (_node *PreAuthKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(preauthkey.Table, preauthkey.Columns, sqlgraph.NewFieldSpec(preauthkey.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PreAuthKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, preauthkey.FieldID)
		for _, f := range fields {
			if !preauthkey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != preauthkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(preauthkey.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reusable(); ok {
		_spec.SetField(preauthkey.FieldReusable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Ephemeral(); ok {
		_spec.SetField(preauthkey.FieldEphemeral, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UsedCount(); ok {
		_spec.SetField(preauthkey.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedCount(); ok {
		_spec.AddField(preauthkey.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Expiration(); ok {
		_spec.SetField(preauthkey.FieldExpiration, field.TypeTime, value)
	}
	if _u.mutation.ExpirationCleared() {
		_spec.ClearField(preauthkey.FieldExpiration, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(preauthkey.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ACLTags(); ok {
		_spec.SetField(preauthkey.FieldACLTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedACLTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, preauthkey.FieldACLTags, value)
		})
	}
	if _u.mutation.ACLTagsCleared() {
		_spec.ClearField(preauthkey.FieldACLTags, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   preauthkey.UserTable,
			Columns: []string{preauthkey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   preauthkey.UserTable,
			Columns: []string{preauthkey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   preauthkey.NodesTable,
			Columns: []string{preauthkey.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNodesIDs(); len(nodes) > 0 && !_u.mutation.NodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   preauthkey.NodesTable,
			Columns: []string{preauthkey.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   preauthkey.NodesTable,
			Columns: []string{preauthkey.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PreAuthKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{preauthkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
