// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/juanfont/headscale-v2/ent/preauthkey"
	"github.com/juanfont/headscale-v2/ent/predicate"
)

// PreAuthKeyDelete is the builder for deleting a PreAuthKey entity.
type PreAuthKeyDelete struct {
	config
	hooks    []Hook
	mutation *PreAuthKeyMutation
}

// Where appends a list predicates to the PreAuthKeyDelete builder.
func (_d *PreAuthKeyDelete) Where(ps ...predicate.PreAuthKey) *PreAuthKeyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PreAuthKeyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PreAuthKeyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PreAuthKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(preauthkey.Table, sqlgraph.NewFieldSpec(preauthkey.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PreAuthKeyDeleteOne is the builder for deleting a single PreAuthKey entity.
type PreAuthKeyDeleteOne struct {
	_d *PreAuthKeyDelete
}

// Where appends a list predicates to the PreAuthKeyDelete builder.
func (_d *PreAuthKeyDeleteOne) Where(ps ...predicate.PreAuthKey) *PreAuthKeyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PreAuthKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{preauthkey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PreAuthKeyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
