// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/juanfont/headscale-v2/ent/aclpolicy"
	"github.com/juanfont/headscale-v2/ent/apikey"
	"github.com/juanfont/headscale-v2/ent/node"
	"github.com/juanfont/headscale-v2/ent/preauthkey"
	"github.com/juanfont/headscale-v2/ent/schema"
	"github.com/juanfont/headscale-v2/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	aclpolicyFields := schema.ACLPolicy{}.Fields()
	_ = aclpolicyFields
	// aclpolicyDescName is the schema descriptor for name field.
	aclpolicyDescName := aclpolicyFields[0].Descriptor()
	// aclpolicy.DefaultName holds the default value on creation for the name field.
	aclpolicy.DefaultName = aclpolicyDescName.Default.(string)
	// aclpolicyDescPolicy is the schema descriptor for policy field.
	aclpolicyDescPolicy := aclpolicyFields[1].Descriptor()
	// aclpolicy.PolicyValidator is a validator for the "policy" field. It is called by the builders before save.
	aclpolicy.PolicyValidator = aclpolicyDescPolicy.Validators[0].(func(string) error)
	// aclpolicyDescUpdatedAt is the schema descriptor for updated_at field.
	aclpolicyDescUpdatedAt := aclpolicyFields[2].Descriptor()
	// aclpolicy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	aclpolicy.DefaultUpdatedAt = aclpolicyDescUpdatedAt.Default.(func() time.Time)
	// aclpolicy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	aclpolicy.UpdateDefaultUpdatedAt = aclpolicyDescUpdatedAt.UpdateDefault.(func() time.Time)
	apikeyFields := schema.APIKey{}.Fields()
	_ = apikeyFields
	// apikeyDescPrefix is the schema descriptor for prefix field.
	apikeyDescPrefix := apikeyFields[0].Descriptor()
	// apikey.PrefixValidator is a validator for the "prefix" field. It is called by the builders before save.
	apikey.PrefixValidator = apikeyDescPrefix.Validators[0].(func(string) error)
	// apikeyDescKey is the schema descriptor for key field.
	apikeyDescKey := apikeyFields[1].Descriptor()
	// apikey.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	apikey.KeyValidator = apikeyDescKey.Validators[0].(func(string) error)
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyFields[2].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(func() time.Time)
	nodeFields := schema.Node{}.Fields()
	_ = nodeFields
	// nodeDescMachineKey is the schema descriptor for machine_key field.
	nodeDescMachineKey := nodeFields[0].Descriptor()
	// node.MachineKeyValidator is a validator for the "machine_key" field. It is called by the builders before save.
	node.MachineKeyValidator = nodeDescMachineKey.Validators[0].(func(string) error)
	// nodeDescNodeKey is the schema descriptor for node_key field.
	nodeDescNodeKey := nodeFields[1].Descriptor()
	// node.NodeKeyValidator is a validator for the "node_key" field. It is called by the builders before save.
	node.NodeKeyValidator = nodeDescNodeKey.Validators[0].(func(string) error)
	// nodeDescName is the schema descriptor for name field.
	nodeDescName := nodeFields[6].Descriptor()
	// node.NameValidator is a validator for the "name" field. It is called by the builders before save.
	node.NameValidator = nodeDescName.Validators[0].(func(string) error)
	// nodeDescCreatedAt is the schema descriptor for created_at field.
	nodeDescCreatedAt := nodeFields[10].Descriptor()
	// node.DefaultCreatedAt holds the default value on creation for the created_at field.
	node.DefaultCreatedAt = nodeDescCreatedAt.Default.(func() time.Time)
	// nodeDescUpdatedAt is the schema descriptor for updated_at field.
	nodeDescUpdatedAt := nodeFields[11].Descriptor()
	// node.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	node.DefaultUpdatedAt = nodeDescUpdatedAt.Default.(func() time.Time)
	// node.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	node.UpdateDefaultUpdatedAt = nodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// nodeDescRegisterMethod is the schema descriptor for register_method field.
	nodeDescRegisterMethod := nodeFields[12].Descriptor()
	// node.DefaultRegisterMethod holds the default value on creation for the register_method field.
	node.DefaultRegisterMethod = nodeDescRegisterMethod.Default.(string)
	// nodeDescIsOnline is the schema descriptor for is_online field.
	nodeDescIsOnline := nodeFields[16].Descriptor()
	// node.DefaultIsOnline holds the default value on creation for the is_online field.
	node.DefaultIsOnline = nodeDescIsOnline.Default.(bool)
	// nodeDescEphemeral is the schema descriptor for ephemeral field.
	nodeDescEphemeral := nodeFields[17].Descriptor()
	// node.DefaultEphemeral holds the default value on creation for the ephemeral field.
	node.DefaultEphemeral = nodeDescEphemeral.Default.(bool)
	// nodeDescSessionEpoch is the schema descriptor for session_epoch field.
	nodeDescSessionEpoch := nodeFields[18].Descriptor()
	// node.DefaultSessionEpoch holds the default value on creation for the session_epoch field.
	node.DefaultSessionEpoch = nodeDescSessionEpoch.Default.(uint64)
	preauthkeyFields := schema.PreAuthKey{}.Fields()
	_ = preauthkeyFields
	// preauthkeyDescKey is the schema descriptor for key field.
	preauthkeyDescKey := preauthkeyFields[0].Descriptor()
	// preauthkey.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	preauthkey.KeyValidator = preauthkeyDescKey.Validators[0].(func(string) error)
	// preauthkeyDescReusable is the schema descriptor for reusable field.
	preauthkeyDescReusable := preauthkeyFields[1].Descriptor()
	// preauthkey.DefaultReusable holds the default value on creation for the reusable field.
	preauthkey.DefaultReusable = preauthkeyDescReusable.Default.(bool)
	// preauthkeyDescEphemeral is the schema descriptor for ephemeral field.
	preauthkeyDescEphemeral := preauthkeyFields[2].Descriptor()
	// preauthkey.DefaultEphemeral holds the default value on creation for the ephemeral field.
	preauthkey.DefaultEphemeral = preauthkeyDescEphemeral.Default.(bool)
	// preauthkeyDescUsedCount is the schema descriptor for used_count field.
	preauthkeyDescUsedCount := preauthkeyFields[3].Descriptor()
	// preauthkey.DefaultUsedCount holds the default value on creation for the used_count field.
	preauthkey.DefaultUsedCount = preauthkeyDescUsedCount.Default.(int)
	// preauthkeyDescCreatedAt is the schema descriptor for created_at field.
	preauthkeyDescCreatedAt := preauthkeyFields[5].Descriptor()
	// preauthkey.DefaultCreatedAt holds the default value on creation for the created_at field.
	preauthkey.DefaultCreatedAt = preauthkeyDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
