// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/juanfont/headscale-v2/internal/biz"
	"github.com/juanfont/headscale-v2/internal/conf"
	"github.com/juanfont/headscale-v2/internal/data"
	"github.com/juanfont/headscale-v2/internal/server"
	"github.com/juanfont/headscale-v2/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

func wireApp(confServer *conf.Server, confData *conf.Data, confHeadscale *conf.Headscale, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	nodeRepo := data.NewNodeRepo(dataData, logger)
	nodeUsecase := biz.NewNodeUsecase(nodeRepo, logger)
	apiKeyRepo := data.NewAPIKeyRepo(dataData, logger)
	apiKeyUsecase := biz.NewAPIKeyUsecase(apiKeyRepo, logger)
	preAuthKeyRepo := data.NewPreAuthKeyRepo(dataData, logger)
	preAuthKeyUsecase := biz.NewPreAuthKeyUsecase(preAuthKeyRepo, logger)
	policyRepo := data.NewPolicyRepo(dataData, logger)
	policyUsecase := biz.NewPolicyUsecase(policyRepo, logger)
	headscaleService := service.NewHeadscaleService(userUsecase, nodeUsecase, apiKeyUsecase, preAuthKeyUsecase, policyUsecase)
	grpcServer := server.NewGRPCServer(confServer, headscaleService, logger)
	httpServer := server.NewHTTPServer(confServer, headscaleService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
