// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ACLPolicy is the predicate function for aclpolicy builders.
type ACLPolicy func(*sql.Selector)

// APIKey is the predicate function for apikey builders.
type APIKey func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)

// PreAuthKey is the predicate function for preauthkey builders.
type PreAuthKey func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
